### ISSUE TITLE
Make a 404 Page

### ISSUE THREAD

**Issue by milstan** [blindnet-io/product-management#14]
We need a custom 404 page. Currently the user, when page is not found, is redirected to create account. 

Look at the best practice: [this](https://www.justinmind.com/blog/best-404-pages/) or else from the internet.

It should be applicable to the Danshboard and to the Website (but also to blindsend and any other interface)

**Comment by nikolaFusion** [comment]
I don't have access to figma, can someone give me access

**Comment by Clementinev** [comment]
Hey Nikola, please send me your email address on slack I'll give you access

**Comment by Clementinev** [comment]
<img width="1440" alt="Screenshot 2022-09-07 at 14 20 52" src="https://user-images.githubusercontent.com/89908145/188881540-1b291e4f-f5b1-47d4-8f7d-629976fa2cfb.png">

It currently needs some adjustments : 
- Put the second box in pale grey (the privateform pale grey)
- In the second box, embed "Privateform" with blindnet.io website link and put the word in bold and in privateform turquoise blue
- In the second box add EN:"Click to learn more"/FR:"Cliquez pour en savoir plus" underlined, and with privateform turquoise blue, and embed with blindnet.io website link
- Move everything up on the page

Such as the sketch below:
![Frame 583](https://user-images.githubusercontent.com/89908145/188883735-8061e4d1-1dbc-406b-ace3-2e07551f5455.png)

**Comment by Clementinev** [comment]
- Works well now for new privacy request page, only there is this right panel message appearing that needs to be removed or hidden : 
<img width="1440" alt="Screenshot 2022-09-09 at 17 19 06" src="https://user-images.githubusercontent.com/89908145/189386606-4c8845ef-0d30-4c51-b580-ee54bffc6094.png">

- Needs to be done for privacy request access link response https://stage.form.blindnet.io/fr/gdpr/response/a215ea0a-5c22-4960-9985-d13a3e6f9aeb (for when link is wrong or expired)

- Needs to be done for forms links also (for when submitter tries to fill out a form that doesn't exist anymore for example) **except if it might break the current form links**, in that case ignore this point

**Comment by Clementinev** [comment]
Can you please put the box in the pale grey F7F8FC (the lighter pf grey- currently it is in the intermediaire pf grey)
