### ISSUE TITLE
PrivateForm homepage text 

### ISSUE THREAD

**Issue by clareblindnet** [blindnet-io/product-management#162]
Current- "Capture patient data in a GDPR compliant way"

Suggestion-

"Capture patient data confidentially using end-to-end encryption"
                 "Did we mention it's GDPR compliant?"  (this line in smaller text)

The question gives a bit of personality to the page and aligns with blindnet's image. 

Will continue brainstorming :)

**Comment by Clementinev** [comment]
Close as resolved in #612
