### ISSUE TITLE
Clearly state that creating an account is consequence-free

### ISSUE THREAD

**Issue by milstan** [blindnet-io/product-management#294]
EveryDeveloper suggested that we are not clear enough about the fact that:

- creating an account on blindnet is free
- we won't bobmard them with e-mails and have our sales-people call them
- they can just create an account, test the service, play with it.

Creating an account somewhere usually comes with consequences, hidden costs, and sales-team insisting, or marketing e-maisl. People are hesistant to open accounts beacause of this. So we need to claim (both on website, and on the create account/login page of dashboard) that we don't do that.

**Comment by noelmace** [comment]
Closing as outdated (clean-up).
Feel free to reopen if not.
