### ISSUE TITLE
Compromise e2ee to easily onboard new users

### ISSUE THREAD

**Issue by m4rk055** [blindnet-io/product-management#34]
Currently, if a new user (Bob) needs an access to already encrypted data, another user (Alice) has to give them the access (needs an action from Alice) by encrypting the data keys for Bob. Even though it is necessary to preserve end-to-end encryption, it is not very user friendly.

We can offer to clients an option to lose e2ee while gaining ability to easily encrypt the data for new users. Clients would posses the keys needed to decrypt users' data and use them when registering a new user to blindnet to encrypt the data for that user.

**Comment by milstan** [comment]
Closing for now. Feel free to reopen @m4rk055 if you disagree.
