### ISSUE TITLE
Data Restitution feature for PrivateForm

### ISSUE THREAD

**Issue by milstan** [blindnet-io/product-management#384]
For the new commercial orientation, we must allow the clients, if they want to leave our service, to export and decrypt all their data. 

This functionality is independant from canceling their subscription and deleting their account. They can request a data export at any time, have all the data downloaded and decrypted. This might take time, so please @Clementinev propose an UX solution to make the user wait long enough.

The functionality should be supported at the SDK level too, in case some clients implemted their forms diretly using SDK

**Comment by loncarb** [comment]
Does anyone knows where should be button for this data export functionality?

**Comment by Clementinev** [comment]
**Waiting text** : 
FR= Vos données sont en cours de téléchargement
EN= Your data is being downloaded

For the **export butto**n, we can put it on the account page, just above the delete my account button like in the sketch below : 
FR= Exporter toutes mes données
EN= Export all my data
![Frame 578](https://user-images.githubusercontent.com/89908145/187893529-65e1c4b6-6331-4426-bd3e-47b907b49e9b.png)

**Comment by Clementinev** [comment]
There should also be one folder for the request history added for downloading all processed requests (not specified in initial specs)

**Comment by Clementinev** [comment]
It doesn't work on my side, it has been 20 minutes and the preparation for download is never ending although I have only 9 forms and 3 privacy request on my account 
(downloading form individually works well though)
<img width="1440" alt="Screenshot 2022-09-15 at 18 04 44" src="https://user-images.githubusercontent.com/89908145/190452953-5cb3efe0-2ea2-47db-9aa3-fc69558d2ebd.png">

**Comment by Clementinev** [comment]
I tried with another staging account, and I got my data downloaded, on the forms folders seems to work well but I the request history folder behaves weirdly, instead of getting the request PDFs I get some king of covid form information : 
<img width="1440" alt="Screenshot 2022-09-16 at 14 16 18" src="https://user-images.githubusercontent.com/89908145/190637213-b8b5853f-e06c-4811-ba95-6f3564c4f818.png">

**Comment by Clementinev** [comment]
Issue when downloading request history it doesn't download all requests 
<img width="809" alt="Screenshot 2022-09-19 at 17 04 33" src="https://user-images.githubusercontent.com/89908145/191050683-891d1193-fdfa-4518-87cf-6c9c13dd3ba0.png">
