### ISSUE TITLE
On "ACCEDER" GDPR feature submission confirmation page - include contact of the client

### ISSUE THREAD

**Issue by milstan** [blindnet-io/product-management#407]
![image](https://user-images.githubusercontent.com/317424/154129136-a13ce6e4-4c93-4659-919b-5a136783ccc1.png)

It would be more user frieldny to include the contact of the client. For that I think, somewhere we must allow the client to specify a contact adress for GDPR requests. Maybe in page personalization.

We can pre-populate this variable by the client's e-mail used for the account - but allow them to specify a different one if they want to gdpr purposes.

**Comment by Clementinev** [comment]
To sum up : 
1. Add FR"Adresse e-mail de contact" / EN:"Contact email address" field on personalization page (and have it shown on left panel of the forms such as the other personalization page fields):
![157408917-a2e4bd72-f3fc-4200-80c0-9be1678cd54c](https://user-images.githubusercontent.com/89908145/191295370-0f4bfddf-65b9-4644-9e8b-9bf7b86c345e.png)

2. Add [@ contact email address] after [@name] on all status pages (when it is filled in personalization page):<img width="1440" alt="Screenshot 2022-09-20 at 17 13 12" src="https://user-images.githubusercontent.com/89908145/191296839-567b9313-bac6-47b6-a11d-08296b888544.png">

3. Change personalization page title to FR:"Personnaliser ma page publique"/EN:"Personalize my public profile" ![157408917-a2e4bd72-f3fc-4200-80c0-9be1678cd54c-1](https://user-images.githubusercontent.com/89908145/191297636-788d0370-067d-4c9d-9d0b-c7ef2f5fedca.png)

Note: not having the field technically mandatory nor pre-filled, but during first demo, when walking through personlaization page along with logo etc.., leading client through fill contact email address as something mandatory for legal @timnicblind @earvinblindnet

**Comment by Clementinev** [comment]
It works well! 
There is just a fix to be made that was not specified, the **new field email address should appear on the left panel on the forms**: 
<img width="1440" alt="Screenshot 2022-10-13 at 15 39 02" src="https://user-images.githubusercontent.com/89908145/195612736-21e748c2-8fef-4549-8994-26a07cab0e3a.png">

**Comment by Clementinev** [comment]
It works well but when nothing has been input in the contact email address field on personnalisation page, no email address should appear on the forms' left panel ie **-> do not use the email address the user used to register if no contact email address has been input on the personnalisation page, if the field is empty then no email address appears on  forms' left panel** 

Screenshot below of my other staging account where no contact email address has been input in personnalisation page and the email address I used to register is used on the forms' left panel : 
<img width="1440" alt="Screenshot 2022-10-17 at 14 12 53" src="https://user-images.githubusercontent.com/89908145/196175094-671a20da-0200-4fe0-b804-78c2700dd05d.png">

<img width="1440" alt="Screenshot 2022-10-17 at 14 12 40" src="https://user-images.githubusercontent.com/89908145/196175078-1910da2e-675e-4f6d-9539-cdfea1a34465.png">

**Comment by Clementinev** [comment]
It works well but there is just one last thing, the field should not be technically mandatory :
<img width="1440" alt="Screenshot 2022-10-18 at 15 33 30" src="https://user-images.githubusercontent.com/89908145/196445641-6fa796cf-0bc4-41d5-b4e4-5c32920e7ec4.png">
