### ISSUE TITLE
GDPR request reminder Email configuration

### ISSUE THREAD

**Issue by Clementinev** [blindnet-io/product-management#420]
@milstan @filipblnt @m4rk055 cf. https://github.com/blindnet-io/product-development/issues/411

A user should be able to configure if he wants the email reminder for GDPR request ([email 5](https://docs.google.com/document/d/1fK0Pw-OkN1YLQ5rD1STdRzFk1mPNyTLjcYBKBLhirCc/edit#heading=h.ty8n49nln718)) when new request comes in and email when untreated request approches deadline #418 

We could have a toggle button "I want to receive GDPR request email reminders" that is by default on, but I don't know where would be the best place - the GDPR perso page is specific to a form so we can't put it there, what about on Modify my account page ?

**Comment by filipblnt** [comment]
I saw the same bug. Also, I wee a bug when my settings are on (somehow it's on now), and if I turn the option off and save, the db is not updated and the option is set back on if I refresh the page.

**Comment by filipblnt** [comment]
The implemented logic is not good, see [here](https://github.com/blindnet-io/privateform-backend/blob/develop/Repositories/PatientsRequestsRepository.cs#L188): it sends reminders for requests that are completed and younger than 4 days. 

What to do:

- The alg should send emails for requests that are **not** completed && which will expire in less than 7 days (this is already being calculated in the request list, see the screenshot below)
- Update email wording for emails sent when GDPR request is about to expire, use [email 7](https://docs.google.com/document/d/1fK0Pw-OkN1YLQ5rD1STdRzFk1mPNyTLjcYBKBLhirCc/edit#heading=h.aegfv6lt9epj).

<img width="656" alt="Screen Shot 2022-06-07 at 13 49 52" src="https://user-images.githubusercontent.com/73657349/172372403-c2aaacd2-d1a4-4043-9163-e19fb60cabb3.png">

**Comment by filipblnt** [comment]
Equation [here](https://github.com/blindnet-io/privateform-server/blob/develop/Repositories/PatientsRequestsRepository.cs#L192) => 
`(nowTime.Date - x.RequestDate.Date).Days < (30 - gdprEmailReminderTime)`

**Comment by filipblnt** [comment]
What needs to be done:
- Limit the link mark only on the word, currently the link mark is extended to the space on the next word (see screenshot)
- Put a space after the comma (see screenshot)
- The "GDPR request" links to untreated requests are not correctly formed. For example, in an email below it's `https://stage.form.blindnet.io/gdpr/request/delete/ec732a3f-6411-4e2c-8e98-a10d748d3f37`, the real link is `https://stage.form.blindnet.io/gdpr/requests/access/ec732a3f-6411-4e2c-8e98-a10d748d3f37`

<img width="1093" alt="Screenshot 2022-06-16 at 11 36 32" src="https://user-images.githubusercontent.com/73657349/174041834-bb7980b9-d8d7-4166-a642-f1c7205a7cbb.png">
