### ISSUE TITLE
E-mail configurations and notification when new form is submitted

### ISSUE THREAD

**Issue by milstan** [blindnet-io/product-management#424]
I suggest we implement a notification system allowing to inform the user that there is a new form collected. The clients should configure /per form/ if they want to receive such e-mail notification (default no), in the Personalize/Forms settings part.

**Comment by Clementinev** [comment]
After looking at this issue and at #729 I realise for email notification that privacy request notifications are general, not tied to a specific form whereas notification for new form submitted are tied to a form. I think we need **a separate tab for notifications, allowing email notification when new form is submitted to be defined for each type of form and Privacy requests notifications at a general level**, here is the new suggestion : 
- Under Personalize tab, **add new EN:"My notifications"/FR:"Mes notifications" subtab** 
with **2 accordion sections :
(1) FR: "Notification par email pour un nouveau formulaire est reçu :"/EN: "Email notification for new submitted form:"**, and **one toggle button for each type of forms**, ie. when a new form is added, a new toggle button for email notification for that specific form is added
**(2) FR: "Notification par email pour les demandes sur les données :"/EN:"Email notification for privacy requests:"** 
and the [right panel message n°51 FR/EN](https://docs.google.com/document/d/1fK0Pw-OkN1YLQ5rD1STdRzFk1mPNyTLjcYBKBLhirCc/edit#heading=h.sbmonedvgh7n)
such as the sketches below : 
![Personalize tab - my notifications subtab 1](https://user-images.githubusercontent.com/89908145/176913526-ffa85a2e-028d-46ab-8f72-dae8ead4acff.png)
![Personalize tab - my notifications subtab 2](https://user-images.githubusercontent.com/89908145/176913536-15a37bb7-8bfc-455a-8cd4-e924c0717a4b.png)


- For the Form parameters subtab, keep it as it is, **only adding accordion sections to improve clarity**, with  the [right panel message n°52 FR/EN](https://docs.google.com/document/d/1fK0Pw-OkN1YLQ5rD1STdRzFk1mPNyTLjcYBKBLhirCc/edit#heading=h.sbmonedvgh7n) such as the sketches below :
![Personalize tab - form parameters subtab 1](https://user-images.githubusercontent.com/89908145/176913193-a036ec12-9a0f-4e35-8b9a-4a0ac010c4ea.png)
![Personalize tab - form parameters subtab 2](https://user-images.githubusercontent.com/89908145/176913202-0b1e3eb0-991d-4c03-ae9c-30f841b52e2c.png)

**Comment by noelmace** [comment]
From today's meeting: (1) having a new, clear issue for this would be useful (2) @noelmace needs to review it to see if it could fit Loreto's expectations, and update the priority accordingly

**Comment by Clementinev** [comment]
New simplified sketch : 
![Personalize tab - my notifications subtab 3](https://user-images.githubusercontent.com/89908145/188689609-018a9ae5-9faa-4c74-9f79-5354eb3c2ec0.png)

Only **add a FR:"Mes notifications"/EN:"My notifications" subtab** with all notifications settings : 
- **Add subtitle FR:"Notification par email lorsqu'un nouveau formulaire reçu :"/EN: "Email notification for new submitted form:"**, and **one toggle button for each type of forms**, ie. when a new form is added, a new toggle button for email notification for that specific form is added "email when new form is submitted" toggle buttons for each existing form (linked to [email 8 New form submitted](https://docs.google.com/document/d/1fK0Pw-OkN1YLQ5rD1STdRzFk1mPNyTLjcYBKBLhirCc/edit#heading=h.t394zdwksdqc) **-> to implement**)
- **Add subtitle FR:"Rappels par e-mail pour les demandes sur les données"/EN:"Email reminders for privacy request"** and **2 toggle buttons**: 
    - **FR:"Nouvelle demande sur les données reçue" / EN:"New privacy request received"** (linked to [email 5 ](https://docs.google.com/document/d/1fK0Pw-OkN1YLQ5rD1STdRzFk1mPNyTLjcYBKBLhirCc/edit#heading=h.ty8n49nln718) already implemented)
    - **FR:"Plus que 7 jours pour traiter une demande avant le délai légal" / EN:"7 days left to process a request before the legal deadline"** (linked to [email 7](https://docs.google.com/document/d/1fK0Pw-OkN1YLQ5rD1STdRzFk1mPNyTLjcYBKBLhirCc/edit#heading=h.aegfv6lt9epj) already implemented)
    - Note: right now those 2 toggle buttons are merge into one toggle button for all privacy request reminders on forms parameters tab **-> delete that button on forms parameters tab**<img width="600" alt="Screenshot 2022-09-06 at 18 46 17" src="https://user-images.githubusercontent.com/89908145/188692522-cc4d7dbf-4129-4ea2-83a6-d148dd30b985.png">

**Comment by Clementinev** [comment]
I can't save modifications : 
![Kapture 2022-09-30 at 14 29 48](https://user-images.githubusercontent.com/89908145/193270820-fe10c01e-d433-4f51-b7c2-1902caf5fae0.gif)

Also those 2 buttons should be turned on by default (as today those emails are sent by default): 
<img width="1440" alt="Screenshot 2022-09-30 at 14 34 12" src="https://user-images.githubusercontent.com/89908145/193270951-39f55e85-9e0a-4cbf-bdf3-b6d66184ee25.png">

**Comment by Clementinev** [comment]
Works well for both fr and en
