### ISSUE TITLE
Automatically add end-user's email address on the consent page

### ISSUE THREAD

**Issue by Vuk-BN** [blindnet-io/product-management#443]
Before an end-user submits a form, they need to consent to GDPR. Right now, the system requires them to enter an email. In case Typeform sends them an email invitation to fill out the form, why don't we either prefill the text box or create a flow in which we inform them that we have the email on file and give them an option to edit/change.

I understand this requires additional dev time, but in the spirit of simplicity, this would simplify that step for the end-user.

**Comment by Clementinev** [comment]
There has been misunderstanding on specs, work as been done to have prefilled email address the gdpr request from the link the user receives by email so we'll keep that work, additionally to prefilled email field on consent page (last page of form) when form link is directly sent by email to user via Privateform
