### ISSUE TITLE
Change right panel buttons on patient form view access GDPR request PrivateForm

### ISSUE THREAD

**Issue by Clementinev** [blindnet-io/product-management#461]
On the patient form view when patient access his form after a GDPR access request : 
![Screenshot 2022-03-18 at 11 16](https://user-images.githubusercontent.com/89908145/159043975-85e8bd02-cd83-48f1-a5e2-d49a2d691eba.png)

The right panel buttons and text should be redesign as follow (cf. sketches below) :
- Change text arrangement  
- Change "Envoyer une demande de modification" button design with smaller font and not all letters in upper-case + the button should be greyed out if no modifications has been made (so it catches user attention that something happened when he modified and that he has to then save modifications)
- Cancel modifications button should not be color filled but only having contours colored + Cancel modifications button should appear only when something has been modified
- Have download button font the same as for save modifications button

![Frame 6](https://user-images.githubusercontent.com/89908145/159044785-e9391db8-0965-448b-99aa-0863819bb177.png)

![Frame 7](https://user-images.githubusercontent.com/89908145/159044806-97a438b0-ab0e-4113-8d3f-6e9762478fd6.png)

**Comment by Clementinev** [comment]
Should match changes made on #614 when modification request developed

**Comment by loncarb** [comment]
Currently we dont have functionality to edit form as a patient so only valid button on tooltip is to download pdf, should we just leave that in tooltip?
