### ISSUE TITLE
doctor-view-form tooltip buttons

### ISSUE THREAD

**Issue by m4rk055** [blindnet-io/product-management#489]
On the `doctor-view-form` tooltip, buttons for canceling modifications and download should get a grey-ish color when hovered, instead of the default one

![image](https://user-images.githubusercontent.com/71560916/162006058-685e5196-f98a-41ad-bd89-be0a674fb8f8.png)

**Comment by Clementinev** [comment]
This has been resolved within https://github.com/blindnet-io/product-management/issues/614 as the save button is now in a different color
