### ISSUE TITLE
Tooltip buttons late state updates

### ISSUE THREAD

**Issue by m4rk055** [blindnet-io/product-management#490]
After a form is modified, the spinner disappears from the SAVE button but it takes about a second for CANCEL button to disappear and SAVE button to return to the disabled state. State change should happen immediately after the spinner disappears.
Might have to do with CSS animations.

![Peek 2022-04-06 17-20](https://user-images.githubusercontent.com/71560916/162009750-cb39bc63-f6ca-42a0-9b69-15a557161c26.gif)

**Comment by Clementinev** [comment]
Already resolved
