### ISSUE TITLE
Automatically create delete request when the delete link is clicked in the GDPR view page

### ISSUE THREAD

**Issue by filipblnt** [blindnet-io/product-management#527]
Currently, the link to delete the data on the page for viewing the data in the context of GDPR view request leads a page for creating delete request

What to do: Automatically create delete request when the delete link is clicked in the GDPR view page

<img width="675" alt="Screenshot 2022-04-14 at 14 03 40" src="https://user-images.githubusercontent.com/73657349/163387566-d0056878-a6db-4eab-ab24-405acc46f6b6.png">

**Comment by Clementinev** [comment]
Already implemented
