### ISSUE TITLE
Change position of label "Formulaire" from /forms page

### ISSUE THREAD

**Issue by m4rk055** [blindnet-io/product-management#534]
The label **Formulaire** seems awkward and takes too much space.
I suggest removing it until we implement a better solution for this form.

What do you think? @Clementinev 

![image](https://user-images.githubusercontent.com/71560916/163579230-26891ddc-1feb-4c0d-8cb2-b410762c8dce.png)
![image](https://user-images.githubusercontent.com/71560916/163579274-31e6bd7f-8800-4a7b-b161-57e78fe0f2b2.png)

**Comment by Clementinev** [comment]
Already resolved
