### ISSUE TITLE
Automatically reject GDPR request from user that don't have any data on Privateform

### ISSUE THREAD

**Issue by Clementinev** [blindnet-io/product-management#558]
In Privateform it is currently possible for client to process a request from a user who doesn't have any data/forms in the system :
<img width="1440" alt="Screenshot 2022-04-26 at 11 55 19" src="https://user-images.githubusercontent.com/89908145/165274656-5223e016-e814-4dbc-91bb-9791d6df4e5b.png">
 
**-> a request from a user that has no forms in Privateform should automatically be rejected sending** [email 6 user no data](https://docs.google.com/document/d/1fK0Pw-OkN1YLQ5rD1STdRzFk1mPNyTLjcYBKBLhirCc/edit#heading=h.nhtk6swgnx74)

Close #626

**Comment by noelmace** [comment]
Weirdly, several delete requests made with my testing accounts (noel@blindnet.io, with which I sent a lot of forms already) appear with "no form", and still need confirmation. So there is either a new bug here, or this issue isn't solved.

@timnicblind please retest this with a fresh new account, and see if a new issue needs to be created.

**Comment by Clementinev** [comment]
- When make delete request with email addresses that have forms it works well (test with 2 different emails addresses)
- **When I try to make delete request with email addresses that doesn't have any form associated, I can't make the request and doesn't receive any email** :
<img width="1440" alt="Screenshot 2022-09-01 at 12 42 15" src="https://user-images.githubusercontent.com/89908145/187895649-4d51fec0-9d25-4a13-bb2f-be1e906eb224.png">

**Comment by noelmace** [comment]
As v1.0.12 has already been released, and v1.0.13 is past due by a week, I'm moving this to v1.0.14 (to release next week).

**Comment by Clementinev** [comment]
It is working well except one thing, as a submitter I received email 6 (which is correct behaviour) AND email 11 and 12 which are for the Data Consumer : 
<img width="1440" alt="Screenshot 2022-09-08 at 14 33 11" src="https://user-images.githubusercontent.com/89908145/189122801-4ad21455-5bee-43dd-9e69-5a14c992e263.png">


**-> redirect email 11 and 12 to Data Consumer (doctor) and not submitter (patient)**

> Here are email 11 and 12 for data consumer (admin & DPO) :
> 
> * [Email 11 for Admin and DPO when user no data made ACCESS GDPR request](https://docs.google.com/document/d/1fK0Pw-OkN1YLQ5rD1STdRzFk1mPNyTLjcYBKBLhirCc/edit#heading=h.27ghfadiibah)
> * [Email 12 for Admin and DPO when user no data made DELETE GDPR request](https://docs.google.com/document/d/1fK0Pw-OkN1YLQ5rD1STdRzFk1mPNyTLjcYBKBLhirCc/edit#heading=h.iboc62kinod7)
