### ISSUE TITLE
[Sagan] Enable downloading forms

### ISSUE THREAD

**Issue by Vuk-BN** [blindnet-io/product-management#611]
On staging, I am trying to download a Sagan form that was submitted (and includes an uploaded file). I get the screen that the download is being prepared, but nothing happened and it's been like 10 minutes. I tried multiple times, the same outcome (waiting yet nothing).
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/65980510/168124138-81f38c1a-191d-4585-bec5-f7de2a5e2da5.png">

**Comment by filipblnt** [comment]
All downloaded PDFs are empty.

**Comment by m4rk055** [comment]
Label is missing for the following field
![image](https://user-images.githubusercontent.com/71560916/172351748-87e9b6e2-9963-4416-b73b-fb53109e4bf9.png)

We also need a better message in place of _Voir le documents a la page suivante_.
Files are not on the next page but in a folder next to the pdf.
@Clementinev can you update the message?

**Comment by Clementinev** [comment]
There is a typo on the english version of the PDF : 
<img width="1012" alt="Screenshot 2022-06-08 at 14 54 55" src="https://user-images.githubusercontent.com/89908145/172621830-fdfbc0f0-59fb-480a-9a82-2ace42ea00aa.png">

"file" should be **replaced by "folder"** for PDF template 3, 4, 5 and 6

**Comment by Clementinev** [comment]
For [Sagan PDF template 1](https://docs.google.com/document/d/1pyG5ELeu-TZWZUCs0hYux5jEUEHkEPA3HdKEyW45SWY/edit) the line "À quelle date est prévue l'audience de conciliation (BCO) ?" should be deleted : 
<img width="1039" alt="Screenshot 2022-06-10 at 10 14 47" src="https://user-images.githubusercontent.com/89908145/173022364-37409c21-27ab-4bf8-9b95-e3cc4b5c7441.png">

**Comment by Clementinev** [comment]
For [Sagan PDF template 2](https://docs.google.com/document/d/1XTp8pOfx4RD8imW5IW6laVEweQQoM_mW2yfHWETC778/edit) the line FR:"À quelle date est prévue l'audience de conciliation (BCO) ?" / EN: "When is the Council Hearing (BCO) scheduled?" is missing and should be added
<img width="1011" alt="Screenshot 2022-06-10 at 10 21 16" src="https://user-images.githubusercontent.com/89908145/173023295-6f821ae4-13ce-4380-80e9-002801946104.png">

**Comment by Clementinev** [comment]
For [Sagan PDF template 3](https://docs.google.com/document/d/19G76fLntIvzp8sWdomSsGig1GEdwQDP144nCNra82XQ/edit): 
French : **the following lines are missing and should be added : 
"À quelle date est prévue l'audience de conciliation (BCO) ?"
JJ/MM/AAAA**

**"Téléverser la convocation à l’audience de conciliation (BCO)"
Voir le(s) document(s) dans le dossier téléchargé avec le formulaire**

**"À quelle date est prévue l'audience de plaidoirie (BJ) ?"
[Pas de date renseignée] or [JJ/MM/AAAA]**

**"À quelle date est prévue l'audience de départage ?"
[Pas de date renseignée] or [JJ/MM/AAAA]** 

<img width="1041" alt="Screenshot 2022-06-10 at 10 28 01" src="https://user-images.githubusercontent.com/89908145/173024673-2c5d24c4-4519-43c2-b0c9-21ab5e7a81fe.png">
 
English : it is good, **only this typo "See the file in the folder downloaded with the form" needs to be changed to "See the file(s) in the folder downloaded with the form"**
<img width="936" alt="Screenshot 2022-06-10 at 10 34 55" src="https://user-images.githubusercontent.com/89908145/173027870-e089ec3a-0b4e-4fc8-8576-96d4c6fb954d.png">

**Comment by Clementinev** [comment]
For [Sagan PDF template 4](https://docs.google.com/document/d/1HsOUHU_LhOVA_nAnx0gtHQ53sO6HGOWwgb0q0HogVJg/edit) : 
French : only this typo **"formulair" should be "formulaire"**
<img width="500" alt="Screenshot 2022-06-10 at 10 48 26" src="https://user-images.githubusercontent.com/89908145/173028694-78b6a874-7741-4e6f-a36c-ad215918cfeb.png">

English :  only this typo **"See the file in the folder downloaded with the form" needs to be changed to "See the file(s) in the folder downloaded with the form"**
<img width="500" alt="Screenshot 2022-06-10 at 10 50 42" src="https://user-images.githubusercontent.com/89908145/173029222-3817a87a-8173-4cc1-a8f9-434f3b56598f.png">

**Comment by Clementinev** [comment]
For [Sagan PDF template 5](https://docs.google.com/document/d/1YgtZJkzRp5ezHZ-ipJhKSDmdBy9Tkfi-t9ndqIIdrtc/edit) : 
French : only this typo **"formulair" should be "formulaire"**
<img width="500" alt="Screenshot 2022-06-10 at 10 59 27" src="https://user-images.githubusercontent.com/89908145/173030820-5f9d8067-e3ab-431f-971a-3c8861396e2e.png">

English : only this typo **"See the file in the folder downloaded with the form" needs to be changed to "See the file(s) in the folder downloaded with the form"**
<img width="500" alt="Screenshot 2022-06-10 at 10 56 30" src="https://user-images.githubusercontent.com/89908145/173030422-44d387b5-9226-444d-b730-906630e5fc8c.png">

**Comment by Clementinev** [comment]
For [Sagan PDF template 6](https://docs.google.com/document/d/1xjF2hna3_B_y2Ju71QlarEkGTjMEc9TKolcDAspxxt8/edit) : 
French : only this typo **"formulair" should be "formulaire"**
<img width="490" alt="Screenshot 2022-06-10 at 11 03 02" src="https://user-images.githubusercontent.com/89908145/173031379-4147c263-7590-4c61-b86d-3100a1e4f32e.png">

English : only this typo **"See the file in the folder downloaded with the form" needs to be changed to "See the file(s) in the folder downloaded with the form"**
<img width="500" alt="Screenshot 2022-06-10 at 11 04 49" src="https://user-images.githubusercontent.com/89908145/173031668-dafbef94-e993-4db7-99e2-1fe36765ff64.png">

**Comment by Clementinev** [comment]
> For [Sagan PDF template 2](https://docs.google.com/document/d/1XTp8pOfx4RD8imW5IW6laVEweQQoM_mW2yfHWETC778/edit): French: **the line "À quelle date est prévue l'audience de conciliation (BCO) ?" is missing and should be added on the french PDF** (English: it is good) <img alt="Screenshot 2022-06-10 at 10 21 16" width="500" src="https://user-images.githubusercontent.com/89908145/173023295-6f821ae4-13ce-4380-80e9-002801946104.png">

Still needs to be done

**Comment by Clementinev** [comment]
> For [Sagan PDF template 3](https://docs.google.com/document/d/19G76fLntIvzp8sWdomSsGig1GEdwQDP144nCNra82XQ/edit)

For the field: À quelle étape de la procédure prud'homale en êtes-vous ?/ What stage of the process are you at?

- When answer is "[En attente de l’audience de plaidoirie]"/"[Waiting for oral argument hearing (BJ)]":
French : French : **the following lines are missing and should be added : "À quelle date est prévue l'audience de conciliation (BCO) ?" JJ/MM/AAAA**
**"Téléverser la convocation à l’audience de conciliation (BCO)" Voir le(s) document(s) dans le dossier téléchargé avec le formulaire**
**"À quelle date est prévue l'audience de plaidoirie (BJ) ?" [Pas de date renseignée] or [JJ/MM/AAAA]**
**"À quelle date est prévue l'audience de départage ?" [Pas de date renseignée] or [JJ/MM/AAAA]**
English : still typo "See the file in the folder downloaded with the form" needs to be changed to "See the file(s) in the folder downloaded with the form"**

- When answer is " [En attente de la décision, après plaidoirie]"/"[Awaiting decision, after argument]:
French: typo **"formulair" should be "formulaire"**
English: English : still typo "See the file in the folder downloaded with the form" needs to be changed to "See the file(s) in the folder downloaded with the form"**

- When answer is " [[En attente de l’audience de départage]"/"[Awaiting decision, after argument]:
French: typo **"formulair" should be "formulaire"**
English: English : still typo "See the file in the folder downloaded with the form" needs to be changed to "See the file(s) in the folder downloaded with the form"**

**Comment by Clementinev** [comment]
> For [Sagan PDF template 4](https://docs.google.com/document/d/1HsOUHU_LhOVA_nAnx0gtHQ53sO6HGOWwgb0q0HogVJg/edit) : French : only this typo **"formulair" should be "formulaire"** <img alt="Screenshot 2022-06-10 at 10 48 26" width="500" src="https://user-images.githubusercontent.com/89908145/173028694-78b6a874-7741-4e6f-a36c-ad215918cfeb.png">
> 
> English : only this typo **"See the file in the folder downloaded with the form" needs to be changed to "See the file(s) in the folder downloaded with the form"** <img alt="Screenshot 2022-06-10 at 10 50 42" width="500" src="https://user-images.githubusercontent.com/89908145/173029222-3817a87a-8173-4cc1-a8f9-434f3b56598f.png">

Still needs to be done

**Comment by Clementinev** [comment]
> For [Sagan PDF template 5](https://docs.google.com/document/d/1YgtZJkzRp5ezHZ-ipJhKSDmdBy9Tkfi-t9ndqIIdrtc/edit) : French : only this typo **"formulair" should be "formulaire"** <img alt="Screenshot 2022-06-10 at 10 59 27" width="500" src="https://user-images.githubusercontent.com/89908145/173030820-5f9d8067-e3ab-431f-971a-3c8861396e2e.png">
> 
> English : only this typo **"See the file in the folder downloaded with the form" needs to be changed to "See the file(s) in the folder downloaded with the form"** <img alt="Screenshot 2022-06-10 at 10 56 30" width="500" src="https://user-images.githubusercontent.com/89908145/173030422-44d387b5-9226-444d-b730-906630e5fc8c.png">

Still needs to be done

**Comment by Clementinev** [comment]
> For [Sagan PDF template 6](https://docs.google.com/document/d/1xjF2hna3_B_y2Ju71QlarEkGTjMEc9TKolcDAspxxt8/edit) : French : only this typo **"formulair" should be "formulaire"** <img alt="Screenshot 2022-06-10 at 11 03 02" width="490" src="https://user-images.githubusercontent.com/89908145/173031379-4147c263-7590-4c61-b86d-3100a1e4f32e.png">
> 
> English : only this typo **"See the file in the folder downloaded with the form" needs to be changed to "See the file(s) in the folder downloaded with the form"** <img alt="Screenshot 2022-06-10 at 11 04 49" width="500" src="https://user-images.githubusercontent.com/89908145/173031668-dafbef94-e993-4db7-99e2-1fe36765ff64.png">

Still needs to be done for all 6 possible answers to field "À quelle étape de la procédure d'appel en êtes-vous ?" / What is the date of the Court of Appeal's decision?
