### ISSUE TITLE
Standardize buttons on form review

### ISSUE THREAD

**Issue by Vuk-BN** [blindnet-io/product-management#614]
Right now we have one very big gradient button for 'Save modifications', one smaller grey button to download a form, and just a label with an emoticon to delete a form. 

We need those buttons/options to be standardized. Pick a single color and size of the buttons, and apply it for all three. 

Also, delete the label description above the buttons. They are just making the right panel looks ugly and not adding that much value.

**Comment by Clementinev** [comment]
Partially resolved in https://github.com/blindnet-io/product-management/issues/569

What should be done : 
- Delete label description
- Update "Save modifications"/"Sauvegarder les modifications" button colors such as sketch below:
- Update "Cancel modifications"/"Annuler les modifications" button colors such as sketch below:
- Update "Download form"/"Télécharger le formulaire" button wording and icon such as sketch below:
- Update "Delete form"/"Supprimer le formulaire" button wording and icon such as sketch below:

![Frame 576](https://user-images.githubusercontent.com/89908145/177979946-bb5e2d90-9e92-436b-a996-7392897118b0.png)

**Comment by Vuk-BN** [comment]
This looks much cleaner than before, thanks @Clementinev
