### ISSUE TITLE
Change optionality with uploaded documents within a form

### ISSUE THREAD

**Issue by Vuk-BN** [blindnet-io/product-management#615]
When I am in the form review mode, I see a 'view' icon next to uploaded files. When I click that icon, I actually download the file instead of just viewing it (in a separate window, for example). 

We need to either change that icon to a download icon, or actually allow the user to view the uploaded document in the browser. 

<img width="569" alt="image" src="https://user-images.githubusercontent.com/65980510/168126072-54db62a6-b11a-4c87-93d2-417f31946875.png">

**Comment by Clementinev** [comment]
**-> Same should be done for ID document field in GDPR request details : **
<img width="1440" alt="Screenshot 2022-05-31 at 16 15 38" src="https://user-images.githubusercontent.com/89908145/171195151-0fa6e187-ce02-496f-a561-785f45fc6666.png">
