### ISSUE TITLE
I can click to Approve a Rights Request with no forms

### ISSUE THREAD

**Issue by milstan** [blindnet-io/product-management#626]
Currently, it is possible to click "Approve" for an ACCESS rights request having no forms. The button is available. This is absurd.

![image](https://user-images.githubusercontent.com/317424/168558056-394e1441-aa5d-45de-af24-049b2e2b208f.png)

If I click on this button, I get a very broad message "Une erreur s’est produite, veuillez réessayer." asking me to try and repeat my (absurd) action.

The system should be designed to prevent errors in general. For every error we handle (with some sort of error message), we should first ask ourselves could we have designed the interface to avoid the error at the first place. I think it is a good way to spot opportunities for improving desing.

**Comment by Clementinev** [comment]
Will be fixed in #558
