### ISSUE TITLE
Refactor legal description text template

### ISSUE THREAD

**Issue by filipblnt** [blindnet-io/product-management#627]
This is the current default legal description text on the final page of form submissions:
<img width="742" alt="Screenshot 2022-05-16 at 14 01 36" src="https://user-images.githubusercontent.com/73657349/168588274-826745f4-c77a-4c74-b56c-2c3a9a76a42e.png">

What to do: Update the default text with the template below.
The @numberOfMonths is a value extracted from the `MinimumRetentionPeriod` db attribute, if not specified the default value is 24.

```
Toutes vos réponses sont confidentielles et sont enregistrées de manière chiffrée par PrivateForm. Elles seront accessibles uniquement par le responsable de traitement, [@client] [@email]. Le responsable du traitement est habilité à collecter ces informations, qui seront utilisées dans le cadre de votre relation contractuelle ou précontractuelle avec le responsable du traitement ainsi que pour les besoins des services fournis. Votre consentement explicite est demandé par ce formulaire. 

Elles seront stockées en Europe pendant toute la durée de votre relation contractuelle avec le responsable du traitement et ensuite pour un délai maximal de [@numberOfMonths] avant d’être automatiquement supprimées. 


En accord avec le RGPD, une fois votre formulaire envoyé vous pourrez exercer vos droits d’accès, de modification et de suppression sur vos données.

Pour plus d’informations vous pouvez contacter :
[@client]
[@email]
[@contact]
```

**Comment by IvanaT0mic** [comment]
In template we have GDPR (en) and RGPD(fr). Should we change it to privacy request or leave it like that? @Clementinev

**Comment by Clementinev** [comment]
For the sentences EN:"In accordance with the GDPR,"/FR:"En accord avec le RGPD" we can leave it like that thank you @IvanaT0mic

**Comment by Clementinev** [comment]
Small note : please make sure to include the line breaks for the legal text

**Comment by Clementinev** [comment]
Small adjustments : 
- French: **add "mois"** after "24" and **delete the extra line break** after "supprimées":
<img width="1440" alt="Screenshot 2022-07-25 at 10 39 53" src="https://user-images.githubusercontent.com/89908145/180736568-63c52f5e-f301-4d35-813e-07c788e135c8.png">

- English: **add "months"** after "24": 
<img width="1440" alt="Screenshot 2022-07-25 at 10 42 02" src="https://user-images.githubusercontent.com/89908145/180736693-ee58b3c9-62b4-4533-920e-7e513f023ebb.png">
