### ISSUE TITLE
small fr translation fix in '/personalize' - "spécialité"

### ISSUE THREAD

**Issue by noelmace** [blindnet-io/product-management#628]
"Spécialité" is specific to doctors. We should use another wording instead.
IMHO, "Courte description" (the direct translation of "Short Description") would be a better fit.

![image](https://user-images.githubusercontent.com/7578400/168629373-88da6418-7624-469a-b4ce-9d35740af494.png)
![image](https://user-images.githubusercontent.com/7578400/168629293-c7ea931e-1531-496d-a505-3ff643df4d68.png)

**Comment by Clementinev** [comment]
Still "Spécialité" in french -> should be changed to "Courte description"
<img width="1440" alt="Screenshot 2022-06-03 at 14 28 52" src="https://user-images.githubusercontent.com/89908145/171853864-0157a9d1-869b-49a9-99ed-1b4c327375e2.png">

**Comment by Clementinev** [comment]
Works well but the wording looks odd, can **the wording "Brève description" be changed to "Description courte"**

**Comment by noelmace** [comment]
Please use: "Courte description" :+1:

**Comment by Clementinev** [comment]
"Description courte" -> should be changed to "Courte description"
<img width="1427" alt="Screenshot 2022-06-10 at 09 35 08" src="https://user-images.githubusercontent.com/89908145/173014834-feb5fb80-7986-463c-bbcc-b508870cec57.png">
