### ISSUE TITLE
Rename uploaded documents

### ISSUE THREAD

**Issue by noelmace** [blindnet-io/product-management#629]
> feedback from Sagan Avocat, see https://github.com/blindnet-io/clients-management/issues/20

Submitters tend to use weird/inconsistent names for the files they upload.

It would be better for customers to automatically rename those documents following a pattern defined with them (e.g. `{file-name}-{submitter-name}-{date}.pdf`).

This new name should be used everywhere in `/history` ("received forms") (i.e. in both the form view and downloaded zip).

![image](https://user-images.githubusercontent.com/7578400/168632548-122a0ca3-d681-4886-971d-2651648fdcc2.png)

**Comment by filipblnt** [comment]
@noelmace Do have the desired file name pattern for the Sagan form?

**Comment by noelmace** [comment]
@filipblnt I'm still waiting for an answer to my last email. I'll send them a reminder right away.

**Comment by filipblnt** [comment]
Add index if the name is the same for multiple files.

**Comment by m4rk055** [comment]
In submitter context, when files are being added, display the original file names. Makes it easier to know which files were added.

In consumer/gdpr form view, display the name related to the form field (e.g. field **convocation**, files _convocation_1_, _convocation_2_). File naming should be per field and customizable (probably in `SaganForm`).

Make sure to add the "customized" file name to metadata [here](https://github.com/blindnet-io/privateform-frontend/blob/611/add-form-zip-download/src/app/services/form.service.ts#L235) (currently it's the original file name), so the file can be saved under the customized name.

**Comment by Clementinev** [comment]
Tested for "customized" file name- next thing is inputting the name Sagan wants
