### ISSUE TITLE
Updating a form "consent" parameter resets the "description" parameter

### ISSUE THREAD

**Issue by noelmace** [blindnet-io/product-management#630]
As an administrator, when I update the collection of consents for a form, its description is reset.

## How to reproduce

1. define a new "Description of the usage of the data: " in the DB
2. go to "personalize my form"
3. update the forms' "collection of consents"
4. save
5. open the associated form
6. fill out the form until the "personal data" screen shows
7. the description had been reset

![image](https://user-images.githubusercontent.com/7578400/168635951-d65fdef8-030a-4643-8766-5ab5051aaedc.png)

**Comment by filipblnt** [comment]
The value in the description field on frontend is still used to update the description attribute of the `FormLinks` table.
Don't update it.
