### ISSUE TITLE
restrict file upload by mime-type

### ISSUE THREAD

**Issue by noelmace** [blindnet-io/product-management#633]
As a submitter, I want to be sure to upload the type of file the data collector is expecting.
As a data collector, I want to make sure people don't send me useless files.

Adding a mime type filter would allow to:
- restrict the type of file shown in the "select file" dialog
- make sure a submitter doesn't try to send a file with a wrong file extension (for example, a png file named foo.pdf)

> I expect Sagan Avocats to expect this feature, even if they never actually asked for it.

**Comment by filipblnt** [comment]
@noelmace Any input on this regarding Sagan, what file formats do they want?

**Comment by noelmace** [comment]
I'm still waiting for their feedback on that, we should (I hope) have it before the end of the week.

**Comment by IvanaT0mic** [comment]
Do I also limit sagan form input files to pdf only? @Clementinev

**Comment by milstan** [comment]
There was a lot of discussion about this with them. At some point they wanted it (becuase it is difficult for them to work with any other type of files), but there were considerations about not wanting to limit users too much. Do you know @Clementinev what was finally said? It is also OK to circle back with them and verify.

**Comment by Clementinev** [comment]
I'll ask @timnicblind and @earvinblindnet if Sagan still want it, @IvanaT0mic for the moment can you please just apply the PDF restriction to the Demo form so we can test?

**Comment by IvanaT0mic** [comment]
On demo form we don't have a file input field. Should I put that filed or maybe to add this restriction on Skill hunter CV form just for testing? @Clementinev

**Comment by Clementinev** [comment]
There is a file field on Demo form but it seems to be an old one: 
<img width="1440" alt="Screenshot 2022-09-20 at 14 32 15" src="https://user-images.githubusercontent.com/89908145/191258496-c5c31742-b61a-4238-a051-efd29a81829b.png">

We need to test on a form that is not a Client form, can we update the Demo from with the regular file field and test on it ?

**Comment by Clementinev** [comment]
We heard back from Sagan, we can directly put the PDFs restriction on their file fields on Retards de Justice form :) (so no need to bother with demo form)
