### ISSUE TITLE
[Sagan] Update the form model to include all file ids

### ISSUE THREAD

**Issue by filipblnt** [blindnet-io/product-management#639]
Update Sagan form model by adding a new field named `all_file_ids`.

This field should contain a sorted list of IDs of all submitted files.

**Comment by m4rk055** [comment]
@loncarb Any reason the field is `string` (array joined with ";"), and not `Array<string>`?
https://github.com/blindnet-io/privateform-frontend/blob/develop/src/app/models/sagan-form.model.ts#L67
