### ISSUE TITLE
Implement Holtrop form

### ISSUE THREAD

**Issue by filipblnt** [blindnet-io/product-management#651]
Implement a form for Holtrop.

Use `/holtrop` for the link type base url. The form consists of the following text fields (deprecated, see comment below):

- First Name(s) / Prénom (required)
- Last Name(s) / Nom (required)
- E-mail / E-mail (required)
- Phone / Numéro de téléphone
- Postal address / Adresse postale

Regarding the seed and localisation, at this moment use the same one from the demo form (to be replaced once agreed on the wordings with a client).

**Comment by filipblnt** [comment]
Update on the form fields:

- Name and surname (one field)
- Company name
- National identity document (one file upload)
- VAT number
- Address
- Phone number
- Email

**Comment by filipblnt** [comment]
Align file field label (national identity document) to the left, in line with other labels:

<img width="739" alt="Screenshot 2022-05-27 at 17 34 30" src="https://user-images.githubusercontent.com/73657349/170734763-9ef49635-fa23-4d5c-ac93-3b822071503c.png">

**Comment by noelmace** [comment]
> Reminder: I didn't have the opportunity to do a requirement gathering for the client, so most of my feedback here are only based on my personal perspective.

1. Phone, Email and Postal addresses don't have any [validation](https://angular.io/guide/form-validation).
2. I expect (other?) clients to ask for suggestions for a "Postal address" input. This could be something to think about for later on. I'll share the client's feedback as soon as I get it.
3. "Vat" doesn't mean anything by itself, especially in French. Please use (fr) "Numéro de TVA" and (en) "VAT Number" instead.
4. Please avoid abbreviations like "Tél" or "CNI" in French (and "CNI" is too restrictive). Instead, use something like "Numéro de téléphone" and "Document d'identité", respectively.
5. I expect the client to ask for indications (and even maybe validations) on which kind of file is expected for "Identity document" (mime-type / file extension and content).
6. I believe the full name of this Company is Holtrop SLP, not just Holtrop (ping @earvinblindnet for confirmation)
7. I believe we should have a better by default "Description for legal text" (see @Clementinev)

**Comment by earvinblindnet** [comment]
>Phone, Email and Postal addresses don't have any [validation](https://angular.io/guide/form-validation).

What do you mean by validation @noelmace ? 

>I believe the full name of this Company is Holtrop SLP, not just Holtrop (ping @earvinblindnet for confirmation)

Exactly, you are right. The full name of the company is Holtrop S.L.P

**Comment by filipblnt** [comment]
What to do:

- Add validation for email and phone number (accepting only digits) 
- Replace VAT with (fr) "Numéro de TVA" and (en) "VAT Number"
- Update French labels for phone and CNI with "Numéro de téléphone" and "Document d'identité".
- Update the form name to "Holtrop SLP"

@noelmace Let's use new issues in the future for things like these.
Regarding address validation, what do you suggest?

**Comment by noelmace** [comment]
This was only generic feedback to check with you. We can now create the issues for all 4 points you validated (let me know if you prefer I do it).

I (i.e. the client) have no specific requirements for address validation (like I said, generic feedback to start the discussion :wink:). Let's postpone this, and I'll tell you if the client needs to add something here after the first demo.

**Comment by filipblnt** [comment]
> We can now create the issues for all 4 points you validated (let me know if you prefer I do it)

No need, just saying that for the next time to avoid piling stuff in one issue.

**Comment by Clementinev** [comment]
Testing: there are few problems : 
1. I can't submit the form
2. There is a bug on the file field
3. There is no right panel message
<img width="1440" alt="Screenshot 2022-06-03 at 15 05 43" src="https://user-images.githubusercontent.com/89908145/171860115-3c4db088-474f-446d-9a39-3c2ec5c767c2.png">

**Comment by noelmace** [comment]
> Tested on June 7th morning

### :warning: CRITICAL

- downloaded PDF has nothing to do with the actual privateform used (Holtrop form)

![image](https://user-images.githubusercontent.com/7578400/172266863-b877492a-7801-444a-ac19-f629925d8f1e.png)

### Required

The phone number field isn't validated

![image](https://user-images.githubusercontent.com/7578400/172266340-02231a8c-4c61-4756-a640-d912498a78fb.png)

### Useful? (to be confirmed with the client today)

- The VAT number field may need to be validated
    - FYI, here is the regexp for France: `^(FR)?[0-9A-Z]{2}[0-9]{9}$`
    - I'll tell the client we wanted to see with him if they needed to be compatible with other countries (e.g. regexp for Spain is `^(ES)?[0-9A-Z][0-9]{7}[0-9A-Z]$`)

**Comment by filipblnt** [comment]
@noelmace We'll make a simple PDF now, can you provide a template for the original one?

**Comment by Clementinev** [comment]
I just made this simple template in case you need it : 
[PDF template (google doc)](https://docs.google.com/document/d/1D2B1jCQ4aZ4xrtGW8s073bMjuCzsumjQy6loeGI7gFw/edit#) 

[HOLTROP PDF template.pdf](https://github.com/blindnet-io/product-management/files/8851649/HOLTROP.PDF.template.pdf)

**Comment by filipblnt** [comment]
@Clementinev Perfect, thanks Clémentine!

**Comment by Clementinev** [comment]
I still get the wrong PDF :
<img width="1068" alt="Screenshot 2022-06-07 at 12 14 21" src="https://user-images.githubusercontent.com/89908145/172355952-f1840047-8bfc-4cf7-8cfd-c071351be1d0.png">

**Comment by noelmace** [comment]
You added validation for the VAT number field but didn't use the right rules (**reminder**: it's a regexp, not a number **please wait for my complete feedback on this**):
![image](https://user-images.githubusercontent.com/7578400/172358423-e46c57b3-af67-48d2-ba36-53b593de61aa.png)

**Comment by filipblnt** [comment]
@noelmace You said you are confirming it with a client, nothing should be changed until we have the correct format.

**Comment by Clementinev** [comment]
I can't access the form as a submitter in GDPR view request, same bug as for [sharpstone advisors form](https://github.com/blindnet-io/product-management/issues/652) : 
> **can't view the form on GDPR access request**, there is bug that logs me out (it only happens for viewing the sharpstone forms and Holtrop forms, I can view other forms) :
>    ![Kapture 2022-06-03 at 15 47 10](https://user-images.githubusercontent.com/89908145/171867129-4a79b969-4e3e-47d4-a1ae-09ac301be7e6.gif)

**Comment by Clementinev** [comment]
PDF works well, just the wording for the document field should be changed to "Voir le document dans le dossier téléchargé avec le formulaire" (cf [this comment](https://github.com/blindnet-io/product-management/issues/611#issuecomment-1148455072)). Here is the template updated : 
- gdoc: [HOLTROP PDF template](https://docs.google.com/document/d/1D2B1jCQ4aZ4xrtGW8s073bMjuCzsumjQy6loeGI7gFw/edit)
- PDF: [HOLTROP PDF template.pdf](https://github.com/blindnet-io/product-management/files/8852461/HOLTROP.PDF.template.1.pdf)

**Comment by Clementinev** [comment]
Here is the english template for PDF :
- gdoc : [EN. HOLTROP PDF template](https://docs.google.com/document/d/1S5Dw0k8dFwl0FHlwsEnZKKG44xT9doekfPHGwGFFoGk/edit)
- PDF : [EN. HOLTROP PDF template.pdf](https://github.com/blindnet-io/product-management/files/8859942/EN.HOLTROP.PDF.template.pdf)

**Comment by noelmace** [comment]
@filipblnt

> @noelmace You said you are confirming it with a client, nothing should be changed until we have the correct format.

Exactly. My issue here was that this (adding a "number" validation to the VAT number input) has been changed right before my demonstration to the client, making it impossible to use a correct VAT number (as they use letters). But this wasn't a big issue, I just skipped it and used 123456789 :wink:

**Comment by Clementinev** [comment]
There is a typo on the english version of the PDF :
<img width="726" alt="Screenshot 2022-06-08 at 15 14 11" src="https://user-images.githubusercontent.com/89908145/172625780-552307c7-0fcf-4b74-a884-9d87ac5a2556.png">
**->** "file" should be **replaced by "folder"** and **put the whole sentence in italic**
