### ISSUE TITLE
Implement Sharpstone projects form

### ISSUE THREAD

**Issue by filipblnt** [blindnet-io/product-management#653]
Implement a form for Sharpstone projects.

Use /sharpstone for the link type base url. The form consists of the following elements:

- First name / Prénom (required)
- Last name / Nom (required)
- E-mail / E-mail (required)
- Phone number / Numéro de téléphone
- Company / Entreprise
- Website URL / Website
- Amount searched for (eur) / Montant recherché (eur) 
- File upload field (labels TBD). Allow multiple files to be uploaded.

Make sure to correctly manage the files in the GDPR view/delete workflows.

Regarding the seed and localisation, at this moment use the same one from the demo form (to be replaced once agreed on the wordings with a client).

**Comment by filipblnt** [comment]
@Clementinev Can you give a simple template for the PDF download (en/fr) please.

**Comment by Clementinev** [comment]
Here are the templates : 
French : 
- gdoc : [FR. Sharpstone 1 projects PDF template](https://docs.google.com/document/d/1nk2-K4MAyb4K_l23bYATbxa6NMeh59zh1wV5hJOcNa4/edit)
- PDF : [FR. Sharpstone 1 _Projects form_ PDF template.pdf](https://github.com/blindnet-io/product-management/files/8859882/FR.Sharpstone.1._Projects.form_.PDF.template.pdf)


English : 
- gdoc : [EN. Sharpstone 1 projects PDF template](https://docs.google.com/document/d/1y7FIhMDn5ohaQTJPjYbBExXXpuELPJlzP7_7ZTgwV8Y/edit)
- PDF : [EN. Sharpstone 1 _Projects form_ PDF template.pdf](https://github.com/blindnet-io/product-management/files/8859874/EN.Sharpstone.1._Projects.form_.PDF.template.pdf)

**Comment by Clementinev** [comment]
For french form PDF template : 
 : [FR. Sharpstone 1 projects PDF template](https://docs.google.com/document/d/1nk2-K4MAyb4K_l23bYATbxa6NMeh59zh1wV5hJOcNa4/edit) there is a typo **"formulair" should be "formulaire"**
<img width="500" alt="Screenshot 2022-06-10 at 11 18 06" src="https://user-images.githubusercontent.com/89908145/173034149-8662c712-2614-42b5-a115-111a5843038e.png">
