### ISSUE TITLE
Use refresh tokens instead of temporary tokens for Azure Keyvault

### ISSUE THREAD

**Issue by filipblnt** [blindnet-io/product-management#661]
Instead of temporary tokens which expire and need to be updated, use the [refresh](https://docs.microsoft.com/en-us/azure/active-directory/develop/refresh-tokens) tokens accros all services/projects.

**Comment by loncarb** [comment]
@noelmace Are you sure that this task is for Privateform? This looks like this is a task for Blindnet API

**Comment by noelmace** [comment]
@Clementinev ☝️ (as you added this issue to the privateform project)

**Comment by noelmace** [comment]
OK, let's postpone this then.
