### ISSUE TITLE
Infitine loop of failed requests

### ISSUE THREAD

**Issue by m4rk055** [blindnet-io/product-management#662]
When the PF server is not available (or if there is any error on `/me` endpoint), client app creates an infinite loop of HTTP calls to `/me` endpoint, which causes lags and can crash the browser.

Change to not request until a successful call - retry just once and display a message if failed.

![image](https://user-images.githubusercontent.com/71560916/171121854-5a5f199f-5f72-405a-914e-41fdfb64c44f.png)

**Comment by noelmace** [comment]
Can't reproduce.

@timnicblind please see with @loncarb if you can manage to reproduce this.

**Comment by timnicblind** [comment]
@loncarb did you test it and can confirm us that it's solved?

**Comment by loncarb** [comment]
yes it works on our side
