### ISSUE TITLE
Add sorting of GDPR requests according to expiey dates

### ISSUE THREAD

**Issue by filipblnt** [blindnet-io/product-management#681]
Make the list sortable asc or desc w.r.t `legal deadline`

<img width="656" alt="Screen Shot 2022-06-07 at 13 49 52" src="https://user-images.githubusercontent.com/73657349/172372403-c2aaacd2-d1a4-4043-9163-e19fb60cabb3.png">

**Comment by m4rk055** [comment]
+ when a new request is available, sort in descending order (by date column) after the "pending requests" page is opened.
