### ISSUE TITLE
[Holtrop] Separate the form into two pages

### ISSUE THREAD

**Issue by filipblnt** [blindnet-io/product-management#683]
The fields and labels should remain the same, but the form should be separated into two pages:

Page 1: 

- Title (en/fr): Contact details / Contact
- Fields: First Name, Last Name, email, identity document, phone and postal address

Page 2: 

- Title: Company / Entreprise
- Fields: Company name, VAT Number

**Comment by noelmace** [comment]
FYI, "person in charge" (of the company) is just the expression we used with the client during our last meeting. I believe we can find a more correct expression for that.

**Comment by Clementinev** [comment]
What do you think of "Contact details" ?

**Comment by noelmace** [comment]
@Clementinev I like this, but not sure about how Holtrop will think about it (as "contact" and "person in charge" could be two different people). We can keep it like that and I'll confirm with them during our next meeting.

**Comment by Clementinev** [comment]
French title for 1st page should be change form "Contact" to "Coordonnées"
<img width="1440" alt="Screenshot 2022-06-27 at 11 01 25" src="https://user-images.githubusercontent.com/89908145/175902096-38ec540e-a76c-4312-96ad-8df06c10361a.png">
