### ISSUE TITLE
[Holtrop] Update validation rules and messages

### ISSUE THREAD

**Issue by filipblnt** [blindnet-io/product-management#684]
Update the validation rules and messages for the following fields:

VAT number:
- Validation should be done w.r.t. European VAT numbers, see instructions [here](https://www.oreilly.com/library/view/regular-expressions-cookbook/9781449327453/ch04s21.html). In addition, the validation should pass for VAT numbers beginning with "EU". 
- An error message should say that the VAT number is invalid and that it should be typed again.

Phone number:

- Validation should allow only international number format: the number must start with a `+`, the number must contain only leading + and digits, the number must contain no more than 15 digits (see examples [here](https://www.oreilly.com/library/view/regular-expressions-cookbook/9781449327453/ch04s03.html))
- An error message should say that the format is invalid, and suggest to use international format.

@Clementinev Can you provide en/fr wordings for the messages please.

**Comment by noelmace** [comment]
If the VAT number regexp seems too complex, I believe we can use a simpler one like `([A-Z]){0,2}[0-9A-Z]{9-12}` (just a simple quick example, please check it actually matches all possible formats).

**Comment by filipblnt** [comment]
We could allow spaces in the field for convenience I guess, but should remove them before sending the data.

**Comment by IvanaT0mic** [comment]
This error messages looks a bit odd. They are too long... Should they stay here or should I put them in the tooltip?

![Screenshot 2022-06-14 130728](https://user-images.githubusercontent.com/102587557/173573365-75696321-2c88-4d47-b7a4-4250995adf92.png)

Should I put min length on phone number?
Vat number regex ([A-Z]){2}[0-9A-Z]{9-12} doesn't matches all possible formats.
(example United Kingdom GBLK123, and Romania (RO)?[0-9]{2,10}). I could use ([A-Z]){2}[0-9A-Z]{2-12}).

![image](https://user-images.githubusercontent.com/102587557/173573997-fddd64f7-aacc-4d84-964d-bc574d60cb84.png)

**Comment by Clementinev** [comment]
Yes the message should stay there (not in the tooltip)

**French message should be added** + I try to **reduce the length of the message** : 

- **Error message phone number:**
**EN:** 
"Please enter a phone number in international format, with a plus sign (+) followed by the digit country code and local phone number. E.g: +33 123 456 789"
**FR:**
"Veuillez entrer un numéro de téléphone au format international, avec le signe (+) suivi du code pays et du numéro de téléphone local. Ex : +33 123 456 789"

- **Error message for VAT number:**
**EN:** 
"Please enter a valid VAT number, with the 2 letter country code (or EU) followed by digits. E.g: FR01234567890"
**FR:** 
"Veuillez enter un numéro de TVA valide, avec le code pays à 2 lettres (ou EU) suivi par des numéros. Ex : FR01234567890"

**Comment by IvanaT0mic** [comment]
So the minimum word for VAT is 5 or should I delete the minimum length? @filipblnt

**Comment by noelmace** [comment]
> What do you think of leaving it without minimum length @filipblnt @noelmace ?

My 2 cents:
- phone: "Please enter a phone number in the international format, with a plus sign (+) followed by digits"
- VAT: "followed by x+ digits" can be enough.

I'll give a demo to this client at 5pm CET today, so I'll ask them.

**Comment by Clementinev** [comment]
> Vat number regex ([A-Z]){2}[0-9A-Z]{9-12} doesn't matches all possible formats. (example United Kingdom GBLK123, and Romania (RO)?[0-9]{2,10}). I could use ([A-Z]){2}[0-9A-Z]{2-12}).

Here : 
-  I can't input the Romanian example RO1234567890
<img width="200" alt="Screenshot 2022-06-28 at 18 14 40" src="https://user-images.githubusercontent.com/89908145/176229461-61b5f437-2638-40ab-b538-90242a2b1840.png">

- **I can't input the UK example GBLK123**, it seems to be a length problem because it works if I add a digit : 
<img width="200" alt="Screenshot 2022-06-28 at 18 14 54" src="https://user-images.githubusercontent.com/89908145/176229553-be779f8e-a78e-4f51-9eda-b2c3cb4c8bbe.png"><img width="200" alt="Screenshot 2022-06-28 at 18 15 00" src="https://user-images.githubusercontent.com/89908145/176229593-5eb1261f-cd05-40fb-839d-fa2c3c0bd803.png">

**Comment by filipblnt** [comment]
> @filipblnt should minimum length be deleted or reduced ?

Deleted.

**Comment by Clementinev** [comment]
For the VAT number, it is not the right error message : 
<img width="315" alt="Screenshot 2022-06-29 at 14 04 28" src="https://user-images.githubusercontent.com/89908145/176432115-7a8d31b4-5c96-4d31-807f-03a93a99dedd.png">

also I am allowed to input just "12" for example without any letter at the beginning : 
<img width="316" alt="Screenshot 2022-06-29 at 14 04 39" src="https://user-images.githubusercontent.com/89908145/176432203-9d68a496-4add-4ecc-a68e-087e3879f0c0.png">

**Comment by IvanaT0mic** [comment]
- First error message is there because VAT number field is mandatory on this form... I will change it... 
- What should I do with third error message? We set only rule for length not for number of digits or number of letters
Should I just put this regex 
^((AT)?U[0-9]{8}|
(CY)?[0-9]{8}L|
(ES)?[0-9A-Z][0-9]{7}[0-9A-Z]|
(FR)?[0-9A-Z]{2}[0-9]{9}|
(IE)?[0-9]S[0-9]{5}L|
(NL)?[0-9]{9}B[0-9]{2}|$
because this is only countries with letters in VAT number. I used simpler regex that @noelmace suggested.
Could you write down all requests for VAT number? @Clementinev  @noelmace

**Comment by Clementinev** [comment]
> * First error message is there because VAT number field is mandatory on this form... I will change it...

Thank you



> * What should I do with third error message? We set only rule for length not for number of digits or number of letters
>   Should I just put this regex
>   ^((AT)?U[0-9]{8}|
>   (CY)?[0-9]{8}L|
>   (ES)?[0-9A-Z][0-9]{7}[0-9A-Z]|
>   (FR)?[0-9A-Z]{2}[0-9]{9}|
>   (IE)?[0-9]S[0-9]{5}L|
>   (NL)?[0-9]{9}B[0-9]{2}|$
>   because this is only countries with letters in VAT number. I used simpler regex that @noelmace suggested.
>   Could you write down all requests for VAT number? @Clementinev  @noelmace

@noelmace is out o the office until Monday so I think we can leave it as it is for the moment and fix this after Noel gives feedback from the client- what do you think @filipblnt ?

**Comment by filipblnt** [comment]
@noelmace We've left it like this so that we can move faster and deploy to prod now.
I'll close it now, please reopen or create a new issue once you have some input.
