### ISSUE TITLE
Data consumer can't view last form page with legal consent and submitter email address - Privateform

### ISSUE THREAD

**Issue by Clementinev** [blindnet-io/product-management#686]
Currently on Privateform, when a data consumer view a form, the last page of the form with the legal consent and submitter email address is not visible, so data consumer have no proof of consent and cannot see the submitter email address

**What could be done :** 
- **Make the last page** of the form with legal consent and submitter email address **visible** when data consumer view a form and **having the fields inactive** so data consumer cannot change them
- **Include last page** of the form with legal consent and submitter email address in the **PDF** of downloaded form 

What do you think ?

**Comment by IvanaT0mic** [comment]
Since we don't keep the answers of consents on backend, I can initially put them all on true. However, what if the submitter accepted two consents and I added a third that he didn't actually accept - is it okay to put it on true automatically?

**Comment by noelmace** [comment]
Up @Clementinev to answer @IvanaT0mic question.

**Comment by m4rk055** [comment]
We need to store the accepted consents in the db and set only them to true in data consumer view.
Otherwise, we present the false information about a sensitive subject.

Also, a data consumer might add a new consent in the future **"I agree to share the data with third parties"**, and will not know which users agreed to it.

**Comment by Clementinev** [comment]
Also at the moment consent options are mandatory, if the submitter want to submit his form, submitter has to accept all consent options. Which means all consent options will be true if a form is submitted

**Comment by m4rk055** [comment]
Consumer can add additional consents after a form is submitted. Those should be set to false.

**Comment by IvanaT0mic** [comment]
We can do as suggested, or we can store the accepted consents in the form directly as an array of objects (plain strings, one for each language) and display them as true. Everything that is left from the database, is set to false. What do you think about this @m4rk055?

**Comment by m4rk055** [comment]
If we put consents in the form, they will be encrypted. There might be a new user role in the future ([DPO](https://edps.europa.eu/data-protection/data-protection/reference-library/data-protection-officer-dpo_en)) who must be aware of users' consents but can't decrypt the data.
So we should keep the consents outside the encrypted form data.
