### ISSUE TITLE
Submitter should only enter their email address once in a form - Privateform

### ISSUE THREAD

**Issue by Clementinev** [blindnet-io/product-management#687]
Currently on Privateform : 
- when client doesn't require an email address field in their form, submitter only have to fill in their email address at the last page with legal consent before submitting
- when client require an email address field in their form, submitter have to fill in their email address twice, once on the first page(s) of the form, and once on the last page with legal consent before submitting

User should not have to fill in their email address twice, and user shouldn't have the possibility to give 2 different email addresses

**What could be done :** 
- if client doesn't ask for email address field, meaning **no email address is asked in the form before last page with legal consent**, then **submitter has to fill in email address in this last page with legal consent** (as it is now)
- if client asks for email address field, meaning **email address is asked in the form before last page with legal consent**, then the **submitter only fill in the email once in the first page(s) of the form** and **on the last page with legal consent their email address is automatically filled in**, and the **field is blocked** (if they want to modify email address they have to go back to first email address field)

What do you think ?

**Comment by m4rk055** [comment]
Email address in the form and email address for legal purposes can be different (e.g. when filling out a form for someone else or if a user explicitly wants to separate communication).

I think the one for GDPR should be pre-filled if the other one exists, but can be modified.

**Comment by filipblnt** [comment]
I agree, prefilling is ok but it should be modifiable.

**Comment by Clementinev** [comment]
Works well (test with Sharpstone Capital form)
