### ISSUE TITLE
[website] showcase our blog

### ISSUE THREAD

**Issue by noelmace** [blindnet-io/product-management#692]
Add a link to our generic blog (i.e. Medium, https://medium.com/blindnet) in the main menu.

![image](https://user-images.githubusercontent.com/7578400/173329061-714d2770-45c8-4ff5-81ad-bdd0c608be53.png)

![image](https://user-images.githubusercontent.com/7578400/173329320-8f73893b-e01c-448f-8c1a-cdd6e27766c6.png)

FYI, I intend to use this blog for generic / non-technical publications only (see https://github.com/blindnet-io/communication-management/issues/51) and to add a blog to our dev portal for dev-oriented publications with cross-posting on dev.to. So this menu entry could become some kind of drop-down menu (blogs > medium / dev) once it's done.

**Comment by filipblnt** [comment]
This is now live

**Comment by noelmace** [comment]
Thanks @filipblnt and @m4rk055
