### ISSUE TITLE
[Sharpstone Advisor form] wording consistency (adviser vs advisor)

### ISSUE THREAD

**Issue by noelmace** [blindnet-io/product-management#695]
## Expected Behavior

All wordings should be consistent (only use Adviser OR Advisor, not both)

## Actual Behavior / How to reproduce

- **AS** a data consumer (Sharpstone)
- **WHEN** a submitter use the **Sharpstone Advisor** form to send me data
- **AND** I go to "received forms" in the back-office to see received data
- **THEN** the form is identified as **"Sharpstone adviser"**

![image](https://user-images.githubusercontent.com/7578400/173579335-92ac0b8f-9a77-44cc-ad4f-02a26ff93de1.png)

**Comment by filipblnt** [comment]
Use `advisor` always.
