### ISSUE TITLE
Relationship between PCA and CA devkit component

### ISSUE THREAD

**Issue by m4rk055** [blindnet-io/product-management#700]
Regarding the relationship between the `Privacy computation engine` (PCA) and `Capture engine` (CA), can the former be integrated into a system without a latter?

From the [HLA interoperability section](https://github.com/blindnet-io/product-management/tree/main/refs/high-level-architecture#bridge-and-interoperability) (and various verbal discussions), I concluded it is possible.
> A system that has their own user identity management, uses 3rd party e2ee library, has its own storage and interfaces for data view, can instantiate the Data Rights Computation Engine and use only the parts of the Data Consumer Interface related to Data Rights Request parametration and approval.

On the other hand, `PCA` works with Data captures (specified [here](https://github.com/blindnet-io/product-management/blob/main/refs/high-level-conceptualization/README.md#data-capture--rights-requests) and [here](https://github.com/blindnet-io/product-management/tree/main/refs/high-level-architecture#data-rights-computation-engine)) which means the `PCA` works with the outputs of the `CA`.

**Comment by milstan** [comment]
The relationhip between these two compoments is established by the common language - the `Schemas` component of the HLA (or not, more concretely the PRIV).

Privacy computation engine indeed works with outputs of the Caputre Component (which MUST produce metadata using PRIV) in order to acheive interoperability.

**Comment by milstan** [comment]
@m4rk055 is your question answered. Please close the issue if so.
