### ISSUE TITLE
Calculate weekly metrics

### ISSUE THREAD

**Issue by filipblnt** [blindnet-io/product-management#733]
Calculate product metrics on a weekly basis, as described [here](https://github.com/blindnet-io/communication-management/issues/145#issuecomment-1158642242).

Timeline: every Friday afternoon.

**Comment by m4rk055** [comment]
I manually populate [the metrics file](https://github.com/blindnet-io/communication-management/blob/main/metrics/usage.csv) every Friday.

**Comment by milstan** [comment]
this is now done with a script
