### ISSUE TITLE
Change page title wording "GDPR Requests" to "Privacy Requests"

### ISSUE THREAD

**Issue by Clementinev** [blindnet-io/product-management#739]
Change the page title wording  : 
- EN: "GDPR Requests" to "**Privacy Requests**"
- FR: "Demandes RGPD" to "**Demandes sur les données**"
<img width="1440" alt="Screenshot 2022-06-30 at 11 13 11" src="https://user-images.githubusercontent.com/89908145/176644988-62f2943e-6c75-4e3b-a014-546a05439756.png">

**Comment by milstan** [comment]
Shouldn't this be "Privacy Request" in accordance with the FRC Lexicon 2?

**Comment by Clementinev** [comment]
Yes you are right thanks! I'll update this issue and #738 

What should be the french translation for "Privacy Request" ?

**Comment by Clementinev** [comment]
Small typo to fix : adding "s" to "Demandes" and "Requests" : 
<img width="1440" alt="Screenshot 2022-07-11 at 12 06 54" src="https://user-images.githubusercontent.com/89908145/178241365-5cdb3197-d0c0-4c04-be1f-f52f67351845.png">
<img width="1440" alt="Screenshot 2022-07-11 at 12 07 01" src="https://user-images.githubusercontent.com/89908145/178241374-c07c745c-19ba-4210-a474-511806a92af6.png">
