### ISSUE TITLE
Weird behaviour on multiple files download - Privateform

### ISSUE THREAD

**Issue by Clementinev** [blindnet-io/product-management#747]
There is a weird behaviour on the multiple files when I download a form as a Data Consumer : 
- Test (1): I input the 3 following files :<img width="800" alt="Screenshot 2022-06-30 at 18 22 22" src="https://user-images.githubusercontent.com/89908145/176730013-5af09665-0754-465b-a93b-bc88c604798e.png">
When I download the form I get 2 out of 3, the 2 I am getting are the last 2 files I input but I am not getting the first one I input : <img width="750" alt="Screenshot 2022-06-30 at 18 31 33" src="https://user-images.githubusercontent.com/89908145/176730326-a0340029-cb53-47d7-9b0f-46ec9792d4fb.png">

- Test (2): I input the 4 following files (same page as 1st test) :<img width="800" alt="Screenshot 2022-06-30 at 18 25 14" src="https://user-images.githubusercontent.com/89908145/176730539-c27b359c-c11b-497c-ad33-9cb3abf0d035.png">
Now I am only getting 1 out of 4, the only one I am getting is the first I input : <img width="754" alt="Screenshot 2022-06-30 at 18 33 59" src="https://user-images.githubusercontent.com/89908145/176731138-3ce9ce05-4e2a-4203-bd1e-e1668eb81ea2.png">

- Test (3): I input the 3 following files (same page as previous tests) :<img width="800" alt="Screenshot 2022-06-30 at 18 27 11" src="https://user-images.githubusercontent.com/89908145/176731306-ecb6b125-6ef2-482d-bd93-17b03ab89da9.png">
This time I am only getting 1 out of 3, the only one I am getting is the first I input : <img width="767" alt="Screenshot 2022-06-30 at 18 38 15" src="https://user-images.githubusercontent.com/89908145/176731598-302c75f1-968c-4d4e-a43f-e93d8b4b729f.png">

- Test (4): I input the 3 following files (same page as previous tests) :
<img width="1440" alt="Screenshot 2022-06-30 at 18 28 12" src="https://user-images.githubusercontent.com/89908145/176731742-8ecb8d08-1125-4848-bc2c-6ed07a79e7ff.png">
Same as test (3) I am only getting 1 out of 3, the only one I am getting is the first I input :
<img width="767" alt="Screenshot 2022-06-30 at 18 40 15" src="https://user-images.githubusercontent.com/89908145/176731909-accec12a-111d-483b-aa1a-7e55e761e0bb.png">

**Comment by Clementinev** [comment]
Yes I can correctly see all the files when I view the form on the interface and also download each file correctly : 
e.g. this is for test (1) : <img width="800" alt="Screenshot 2022-06-30 at 18 51 08" src="https://user-images.githubusercontent.com/89908145/176734062-da0fcb38-6d2b-4123-b49e-ea278467e6b0.png">


**the bug is only when I download the whole form**

**Comment by m4rk055** [comment]
The issue is in extraction of files with same names from an archive.
If multiple files with the same name (and extension) are extracted, one will override the other in the file system. I don't know how it's handled on Windows.

Didn't we increment the counter attached to the end of a file name, in case of multiple files? It's not the case anymore.
