### ISSUE TITLE
Refine Requirements for Privacy Request Capture Interface

### ISSUE THREAD

**Issue by jboileau99** [blindnet-io/product-management#751]
I'm working on refining the requirements for the Privacy Request Capture Interface, eventually drilling down to code requirements. So far it's just for the local interface.

# Local Privacy Request Capture Interface

## Resources

- [Diagrams and sketches](https://github.com/blindnet-io/product-management/issues/734)
- [Use cases](https://github.com/blindnet-io/product-management/blob/3d67ecab1c7356cc94e6d468cc344eea65e9b409/user-stories/US-07-Privacy-request-capture-service.md)
- [Devkit architecture](https://github.com/blindnet-io/product-management/tree/devkit-architecture/specifications/architecture)
- [HLA](https://github.com/blindnet-io/product-management/tree/devkit-architecture/refs/high-level-architecture)
- [Lexicon](https://github.com/blindnet-io/product-management/blob/devkit-architecture/refs/lexicon/RFC-Lexicon-2.md)

## Related Models

- [Privacy Requests](https://github.com/blindnet-io/product-management/blob/devkit-architecture/refs/lexicon/RFC-Lexicon-2.md#privacy-request)
- [Data subjects](https://github.com/blindnet-io/product-management/blob/devkit-architecture/refs/lexicon/RFC-Lexicon-2.md#data-subject)
- [Systems](https://github.com/blindnet-io/product-management/blob/devkit-architecture/refs/lexicon/RFC-Lexicon-2.md#system)

## Questions

- As described in the [devkit architecture](https://github.com/blindnet-io/product-management/tree/devkit-architecture/specifications/architecture) there is a privacy request capture interface, and there is also a privacy request capture component
    - Their descriptions are similar, what is the distinction? It sort of sounds like the Privacy Request Capture Interface refers more to the global version, whereas the privacy request capture component refers to the local
- Related to US-07-2-03, does the privacy request capture interface also handle receiving requests?
- From US-07-2-05 and US-07-2-06 - “Privacy requests can be made in relation to the consents or data associated with a particular data capture” → How does the local privacy requests capture interface know about the data captures? Does the user provide an ID of the capture related to their request?

## Use Case Refinement

**Functionality:** Authentication through Devkit Login Component

- **Prerequisites** 
    - Access to Login Component
- **Inputs** 
    - Inputs required by Login Component
- **Outputs** 
    - Authenticated user → Token?

**Functionality:** Create rights request

- **Prerequisites**
    - Component must be aware of and allow user to select from [request types](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/examples.md), [demand types](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/RFC-PRIV.md#demands), [actions](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/RFC-PRIV.md#proposal), [categories](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/dictionary/data-categories/en.data-categories.json), [processing categories](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/dictionary/processing-categories/en.processing-categories.json), [purposes](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/dictionary/purposes/en.purposes.json), and [target](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/dictionary/targets/en.targets.json)
    - Action requested can be restricted based on any combination of [Privacy Scope](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/RFC-PRIV.md#privacy-scope), [Consent Restriction](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/RFC-PRIV.md#consent-restriction), [Capture Restriction](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/RFC-PRIV.md#capture-restriction), [Date Range](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/RFC-PRIV.md#date-range), [Provenance Restriction](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/RFC-PRIV.md#provenance-restriction), and/or [Data Reference Restriction](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/RFC-PRIV.md#data-reference-restriction)
    - [Request format](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/json-schema/priv.schema.json) must allow requests to be sent anonymously, interface must be aware of this format
    - Can be created in relation to consents and data captures
- **Inputs**
    - One or more [Demands](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/RFC-PRIV.md#demands), each having [demand restrictions](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/RFC-PRIV.md#demand-restrictions)
- **Behaviour**
    - Interface should guide the user through creating the request in such a way that requests are always correctly formulated, as precise as possible, and able to be handled automatically
- **Outputs** Prepared rights request

**Functionality:** View and monitor previously created requests

***Question:*** Where are these rights requests stored?

- **Prerequisites**
    - Component must have access to rights request created by this user
- **Inputs**
    - MAY provide request-id to get exact request
    - MAY provide date or date range to get multiple requests
- **Outputs** 
    - Status/details relating to queried rights requests

**Functionality:** Tutorial for users creating a rights request

- **Prerequisites** 
    - User’s first time using the interface or they request tutorial
- **Inputs**
- **Outputs**

**Comment by milstan** [comment]
Also @jboileau99 have a look at this [marketing document](https://github.com/blindnet-io/communication-management/blob/main/docs/product-marketing/2022/blidnet-devkit-product-spec.md). I think Privacy Request Manager is a good name for interface components that deal with Privacy Requests (their capture, management, view...).

> As described in the [devkit architecture](https://github.com/blindnet-io/product-management/tree/devkit-architecture/specifications/architecture) there is a privacy request capture interface, and there is also a privacy request capture component
>         Their descriptions are similar, what is the distinction? It sort of sounds like the Privacy Request Capture Interface refers more to the global version, whereas the privacy request capture component refers to the local

Those definitions should converge. Feel free to propose changes so that there is only one name. 

In the current milestone we only focus on Local Scope. Global Scope is to be left for later.

>     Related to US-07-2-03, does the privacy request capture interface also handle receiving requests?

That is its primary prupose, in fact.

>     From US-07-2-05 and US-07-2-06 - “Privacy requests can be made in relation to the consents or data associated with a particular data capture” → How does the local privacy requests capture interface know about the data captures? Does the user provide an ID of the capture related to their request?

It is possible to make capture/consent-related Privacy Requests only in the [A Priori Authentication scenario](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/scenarios.md#a-priori-authentication)

**Comment by Clementinev** [comment]
> > ```
> > Related to US-07-2-03, does the privacy request capture interface also handle receiving requests?
> > ```
> 
> 
> That is its primary prupose, in fact.

Here I was thinking the scope of privacy request capture interface was focusing on sending the request - not receiving it (which would be the data consumer interface) ?

**Comment by Clementinev** [comment]
> **Functionality:** Create rights request
> 
> * **Prerequisites**
>   
>   * Component must be aware of and allow user to select from [request types](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/examples.md), [demand types](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/RFC-PRIV.md#demands), [actions](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/RFC-PRIV.md#proposal), [categories](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/dictionary/data-categories/en.data-categories.json), [processing categories](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/dictionary/processing-categories/en.processing-categories.json), [purposes](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/dictionary/purposes/en.purposes.json), and [target](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/dictionary/targets/en.targets.json)

Should we also add provenance here ? (Example: a user wants to know the what are the data that are transferred from another system or derived from their actions)

**Comment by jboileau99** [comment]
> > **Functionality:** Create rights request
> > 
> > * **Prerequisites**
> >   
> >   * Component must be aware of and allow user to select from [request types](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/examples.md), [demand types](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/RFC-PRIV.md#demands), [actions](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/RFC-PRIV.md#proposal), [categories](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/dictionary/data-categories/en.data-categories.json), [processing categories](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/dictionary/processing-categories/en.processing-categories.json), [purposes](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/dictionary/purposes/en.purposes.json), and [target](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/dictionary/targets/en.targets.json)
> 
> Should we also add provenance here ? (Example: a user wants to know the what are the data that are transferred from another system or derived from their actions)

Is this covered by the TRANSPERENCY.PROVENANCE action term in [PRIV](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/RFC-PRIV.md#proposal)?

**Comment by milstan** [comment]
when the user makes `TRANSPARENCY.PROVENANCE` demand, the system should respond with one of the [Provenance Terms](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/RFC-PRIV.md#provenance-categories)

Also the Privacy Request Capture Interface should allow to set a [Provenance Restriction](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/RFC-PRIV.md#provenance-restriction) using any of the Provenance Terms.

**Comment by jboileau99** [comment]
> when the user makes `TRANSPARENCY.PROVENANCE` demand, the system should respond with one of the [Provenance Terms](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/RFC-PRIV.md#provenance-categories)
> 
> Also the Privacy Request Capture Interface should allow to set a [Provenance Restriction](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/RFC-PRIV.md#provenance-restriction) using any of the Provenance Terms.

@milstan Thanks. @Clementinev Updated the specification here and proposed[ this change to US-07-1-06](https://github.com/blindnet-io/product-management/pull/602/files#r912928203) to cover restrictions.
