### ISSUE TITLE
Together write Functional Requirments document

### ISSUE THREAD

**Issue by milstan** [blindnet-io/product-management#754]
## Goal

As a result of understangings gained through the work on architecture, models and priorities, collaboratively write a Functional Specification Document.

The document should satisfy the following requirements:
- Cover only the limited scope of what will be built for Q3 2022 milestone
- Be a Functional Specification
- Be minimal (omit the obvious, or what is already specified in another document)
- Be sufficient (for buildign software towards its purpose and indeted general function)
- Be a working document - we are making a first version here, and may update it as we develop the product if see we missed something here

Please carfeully observe the [product marketing document](https://github.com/blindnet-io/communication-management/blob/main/docs/product-marketing/2022/blidnet-devkit-product-spec.md).

**Comment by milstan** [comment]
TBH what I had in mind is much less in fact - just a list of such issues in one md file. The idea is that the functional requirements should be built by developers, and updated as the code is developed. In my view their main prupose is to indicate to other developers working on the same codebase what they can expect from some other part of the code.

We want something quick, minimal, as little overhead as possible.

I like the approach you propose Noël, and as we have EPIC issues for each component, where we list atomic issues as subtasks, it will be easy to follow there, what is going on in which component and what one can expect from the component. I can volonteer to summarize it later as a FRD for the community.

I'd like to hear from @m4rk055 @TheKinrar @jboileau99 what they think - is that easier and more straightforward to them? Just make sure we have clarity on what should be done by EOD today as we aim to finish scoping within Product 0, so that everybody knows they need to create issies instead of updating this document. I let you look for concenus @noelmace .

**Comment by jboileau99** [comment]
For me, an atomic issue and pull request per functional requirement/feature (Noël's approach) is the easiest. I think it will work well to have an issue + draft PR for the functional requirement I'm working on, which starts with a simple requirement statement (like the few we have in the FRD currently), and then we can refine these in the issues as we develop the feature. Then the merging of the PR + closing of the issue signifies the functional requirement is implemented and the specification from the issue can be added to the summary FRD as more of a "final" version.

**Comment by milstan** [comment]
> ➡️ Everyone at blindnet trust you can develop a good devkit based on your experience and technical skills.

Also this is very important. We trust you, and all the stuff I made (including normative documents) are there to be impoved. If while devloping you realize there are nice solutions that would mean chaning HLC/HLA/PRIV, they can evolve and SHOULD evolve. 

In fact as long as they don't evolve we can't be sure they have reached sufficient maturity for larger adoption. So feel free to also break things ;)

**Comment by noelmace** [comment]
## :warning: CLARIFICATION

Here is a flowchart to clarify the new process:

```mermaid
flowchart
     create[create an issue] --> objection{Formal Objection in 24h?}
     objection -- yes --> discuss --> req[PR to define a formal requirement] --> objection
     objection -- no --> develop --> PR --> change{important change?}
     change -- yes --> DR[add a DR] --> merge
     change -- no --> merge --> close[close issue]
```

### WIP

Right now, I believe we can directly merge #755 as it is.

Meaning:
- @TheKinrar don't need to spend more time on it.
- just push what you added and discuss them right away with the team (use slack/calls if necessary)
- the PR will be merged on Jully 04 evening CET whatever happens

### Next

All "missing" requirements can be added to this document afterwards **IF AND ONLY IF** necessary (i.e. formal objection on an issue).
The new process will cover **ALL** requirements and is an absolute prerequisite to writing a **formal requirement** in this document.

**PLEASE** confirm everything is clear enough to you and their isn't any ambiguity left.

**Comment by TheKinrar** [comment]
> All "missing" requirements can be added to this document afterwards IF AND ONLY IF necessary (i.e. formal objection on an issue).

I don't get that. Don't we still want to add FRs for things we agree upon?
Let's say I'm working on the Metadata/Capture components, and I had to change the scope of it in some way, or define how it communicates with other components. Can't I just create a PR for a new FR describing that? In the workflow here, I don't get how I should proceed. Seems to me I would have to create an issue describing that, and then if everyone agrees, I need to create a PR (where?) and maybe a DR, but no FR.

I think I'm missing something because what I understood initially is, we want to write a complete FRD, but we don't have the time (and it's not that practical) to write it before writing any code, so we'll just add FRs alongside writing code when useful to do so.

**Comment by noelmace** [comment]
@TheKinrar

> Don't we still want to add FRs for things we agree upon?

I updated the flowchart to specify you can add an FR as part of the PR and to clarify the case when we have several interdependent PRs across several repositories.

> create a PR (where?)

Development has to occur in the associated code base repositorie(s). DR and FR should be as much as possible maintained in the same repositories as the associated code. But we can still use several interdependent PRs in the case the DR or FR has to be maintained in a more generic repository (e.g. product-management or openness-framework).

I'll soon simplify that by moving as much documentation as possible to the blindnet.dev repo.
