### ISSUE TITLE
[epic] define and implement storage part for the DevKit

### ISSUE THREAD

**Issue by noelmace** [blindnet-io/product-management#762]
## Description

Create and document a first operational storage suite as part of the DevKit, including the Data Access Component, Storage Connectors, and a demo Data Storage service (with DevX in mind, building a small helper library). 

### Intended outcome

- have a minimal but operational storage solution allowing to demo a DevKit MVP (v0)
- have a strong enough basis to develop following storage feature and support further DevX improvements

## Sub-tasks

- [x] #765 
- [ ] #766
- [x] #767
- [x] #768
- [x] #769

## Stakeholders

- @TheKinrar for development
- @noelmace and @milstan for tracking and help
- @blindnet-io/engineering for reviews and knowledge sharing

**Comment by milstan** [comment]
IMHO what we wanted in Q3 has been acheived. The Data Access Component is [here](https://github.com/blindnet-io/data-access-component).
