### ISSUE TITLE
Define the API implemented by Data Access Component

### ISSUE THREAD

**Issue by TheKinrar** [blindnet-io/product-management#767]

**Comment by milstan** [comment]
@TheKinrar please note that the client systems should be able to use the components of the blindnet devkit in a distributed setting. Immagine an external DPO organisation, having their own application for viewing and responding to  Privacy Request, that uses our Privacy Request Capture Interface and Privacy Computation Engine (take example of [DPO consulting and their app MyDPO](https://github.com/blindnet-io/clients-management/issues/62) in the context of [this use-case](https://github.com/blindnet-io/devrel-management/blob/main/docs/use-cases/external-dpo.md)).

Now they have a client, that is a System actually collecting user data. This System is independant from the External DPO's system. And this Client System implements the Data Access / Storage components. Those components still communicate with the Privacy Computation Engine (that is used by the External DPO).

This probably changes nothing to how you planned things. It is just FYI, just in case. If not clear let's discuss today (or you can call me later if needed)

**Comment by milstan** [comment]
IMHO this is done in the sens of what we wanted for Q3 (more work will be done for Q4, but that will be a separate issue). @TheKinrar if you object, feel free to reopen it.
