### ISSUE TITLE
Refactor / Fix legal description text template

### ISSUE THREAD

**Issue by noelmace** [blindnet-io/product-management#789]
> extend https://github.com/blindnet-io/product-management/issues/627

## Reproduce

As a PrivateForm administrator (backoffice)
When Personalizing a form
1. **I shouldn't need to edit the description text template if I'm OK with the default template**
2. **I can't edit the description text template**
3. (_to be confirmed, critical if confirmed_) **when I edit another parameter, the description text template is reset to a bad default value**

![image](https://user-images.githubusercontent.com/7578400/177826104-f566c1e6-a7a6-44aa-a666-58657894c998.png)

## Context & Questions

Apparently, this field has been disabled (2) because of the variables in it.

**Question:** Does using the wrong variable here could create a problem? Which one exactly?

## Proposed solutions

> EDIT: updated requirements for 2 following https://github.com/blindnet-io/product-management/issues/789#issuecomment-1178687662 and https://github.com/blindnet-io/product-management/issues/789#issuecomment-1178724434

1. #627 
2. ~~un-disable this field, and, if necessary,~~ add a short text explaining how to edit this field correctly, ~~including a list of the possible variables (to be completed by @Clementinev)~~
    - EN : "Here you can edit the wording of the text, the duration of data retention, the name and contact details of the data controller"
    - FR: "Ici vous pouvez éditer la formulation du texte, la durée de rétention de des données, le nom et les coordonnées du responsable de traitement"
    - Variables from the default description template are parsed into the real values in the description field. When a user saves the parameters, variables get overridden by the real values.
4. straightforward (solution included in 2)

**Comment by Clementinev** [comment]
> 2\. un-disable this field, and, if necessary, add a short text explaining how to edit this field correctly, including a list of the possible variables (to be completed by @Clementinev)

Below "Description of the usage of the data:", just before the text field we can add the following note : 
EN : "Here you can edit the wording of the text, the duration of data retention, the name and contact details of the data controller"
FR: "Ici vous pouvez éditer la formulation du texte, la durée de rétention de des données, le nom et les coordonnées du responsable de traitement"

**Comment by noelmace** [comment]
@m4rk055 (for technical explanation focused on the variables) and @milstan (for legal explanation focused on the purpose, mandatory parts): please suggest an improvement for the message above. Using more than a single sentence is OK IHMO, as we could present it as an expendable text using a :information_source: logo to click on.

**Comment by m4rk055** [comment]
I don't think it's a good idea to let users use the variables.
Instead, variables from the default description template are parsed into the real values in the description field. When a users saves the parameters, variables get overridden by the real values.

I think the explanation @Clementinev suggested is OK.

Watch out for [XSS](https://owasp.org/www-community/attacks/xss/) while parsing variables.

**Comment by Clementinev** [comment]
It works well, there is just a weird behaviour with language switch : 
- On form as submitter : 
When I am on the last page of the form, and I switch interface language, the legal text doesn't switch in the interface language, I have to go back to the previous page and then go back to the last page and legal text is switch in the interface language : 
![Form](https://user-images.githubusercontent.com/89908145/180740192-5190b0f8-f5ba-4d66-b410-e58d9f7c07bb.gif)
**-> The legal text should switch right away in the interface language**

- On the data consumer backoffice
It is kind of the same behaviour, when I am on the form parameters page and I switch the interface language, eveything switch language except the legal text, I have to go back or go to another tab and return, to see the legal text in the interface language : 
![Backoffice](https://user-images.githubusercontent.com/89908145/180740538-b237cb3f-6bbe-464c-87d1-72ce8101790c.gif)
-> The legal text should switch right away in the interface language, but here as it is an editable field, I don't know if it is possible. But it could be a quick fix before handling : https://github.com/blindnet-io/product-management/issues/480

**Comment by Clementinev** [comment]
@noelmace I ping you here following our discussion, also https://github.com/blindnet-io/product-management/issues/627, when v.1.0.8 will be in production, to  notify clients who are already onboarded that legal text description will be implemented, and they can change it if they want to remove things from the default text such as their email address etc
