### ISSUE TITLE
Email language for Data Consumer should be in the language of the Data Consumer UI

### ISSUE THREAD

**Issue by Clementinev** [blindnet-io/product-management#791]
Includes #576 

Right now, for example Privacy Request emails for Data Consumers are received in the language the Submitter chose to create the request, meaning even if Data Consumer chose English language their UI, if submitter submitting request chose French in their UI, Data Consumer will receive the emails regarding privacy requests in French even if Data Consumer doesn't speak French

**- > All emails Data Consumers receive should be in the language they choose for their UI** 
Note : /!\ this also includes Reminder emails for privacy request approaching deadline

**Comment by m4rk055** [comment]
Language should be specified for each user in the `Users` table and updated whenever a user changes the UI language.

**Comment by Clementinev** [comment]
It works for the Data Consumer side - e.g. if Data Consumer has interface in FR and submitter submit request in EN- Data consumer receive email in french

But the submitter also receive email in french -> submitter should have received it in EN. I'll create a new issue to fix it so that submitter receive email in the chosen language to fill a form/submit a request
