### ISSUE TITLE
Init CD for the privacy request capture interface for demo

### ISSUE THREAD

**Issue by noelmace** [blindnet-io/product-management#811]
Add continuous delivery to the wc-priv-request project to demo it.

**Comment by m4rk055** [comment]
We can use the [Azure static web app](https://azure.microsoft.com/en-us/services/app-service/static/#overview) to deploy the capture interface. CI pipeline is [quite simple](https://github.com/blindnet-io/blindnet.dev/blob/main/azure-pipelines.yml).
