### ISSUE TITLE
[Loreto 1 Locataire form] fix : english typo 

### ISSUE THREAD

**Issue by Clementinev** [blindnet-io/product-management#815]
On Loreto form, on the **english version, on page 2 the subtitle title** should be "Documents needed for **co-applicants**" instead of "applicants" 
Same on the **english PDF** 
<img width="1440" alt="Screenshot 2022-07-19 at 15 32 55" src="https://user-images.githubusercontent.com/89908145/179763685-ca620213-410a-48fd-b7e1-b2e270b8d51f.png">
<img width="1081" alt="Screenshot 2022-07-19 at 15 35 31" src="https://user-images.githubusercontent.com/89908145/179763692-d62db183-283c-42ce-b75a-e9a736b57c01.png">

**Comment by IvanaT0mic** [comment]
Should this be done by Friday because it is 1.0.9 version? @noelmace 
and this one too https://github.com/blindnet-io/product-management/issues/816

**Comment by noelmace** [comment]
As v1.0.7 has already been released to production with #787, and this form will be demonstrated to the client next Monday, I'd usually consider this a "critical bug" (as it's an infringement of the initial specs), and therefore a [hotfix](https://danielkummer.github.io/git-flow-cheatsheet/). But we don't have a process for that, so I don't expect to have it before the next release (v1.0.8, before next Monday evening).

So, as for any other issue, I trust you (Fusion) to correctly evaluate in which version this should be included given the time you have left and the issue that are already in progress.

Here, as @Clementinev defined its priority as "1 - urgent" (cf. the label description), this should be included in v1.0.8 if possible, or v1.0.9 if not.
