### ISSUE TITLE
[Sharpstone] Change name of the form on the backoffice and URL base name

### ISSUE THREAD

**Issue by Clementinev** [blindnet-io/product-management#819]
For Sharpstone the **name of the form on the backoffice** and **url base name** need to be changed to the following: 
- "Sharpstone advisor form" should be changed to **"Sharpstone Advisory"** and url base "/sharpstone-advisor/" should be changed to **/sharpstone-advisory/**
- "Sharpstone form" should be changed to **"Sharpstone Capital"** and url base "sharpstone" should be changed to **/sharpstone-capital/**

<img width="1440" alt="Screenshot 2022-07-20 at 18 45 12" src="https://user-images.githubusercontent.com/89908145/180037973-5fa5107c-9245-4249-bf36-908ba5f49f93.png">

**Comment by Clementinev** [comment]
If changing url name is risky in the sense it might break things, let's keep the url names as they are

**Comment by m4rk055** [comment]
Urls have to be unique among all users (including clients/forms). So if we change the url to `/sharpstone-advisory`, it only works for a single users. Additional user will have to have a different url.
