### ISSUE TITLE
Weird behaviour for language interface switch for legal text 

### ISSUE THREAD

**Issue by Clementinev** [blindnet-io/product-management#832]
Following #789 

There is a weird behaviour with language switch for the legal text : 
- On form as submitter : 
When I am on the last page of the form, and I switch interface language, the legal text doesn't switch in the interface language right away, I have to go back to the previous page and then go back to the last page and legal text is switch in the interface language : 
![Form](https://user-images.githubusercontent.com/89908145/180740192-5190b0f8-f5ba-4d66-b410-e58d9f7c07bb.gif)
**-> The legal text should switch right away in the interface language**

- On the data consumer backoffice
It is kind of the same behaviour, when I am on the form parameters page and I switch the interface language, eveything switch language except the legal text, I have to go back or go to another tab and return, to see the legal text in the interface language : 
![Backoffice](https://user-images.githubusercontent.com/89908145/180740538-b237cb3f-6bbe-464c-87d1-72ce8101790c.gif)
**-> The legal text should switch right away in the interface language**, but here as it is an editable field, I don't know if it is possible. But it could be a quick fix before handling : https://github.com/blindnet-io/product-management/issues/480

**Comment by Clementinev** [comment]
It seems the weird behaviour for language switch is only for submitter screens. 
Additionally to legal text when filling a form, as submitter there is also **"my data rights" page** and in **ACCESS privacy request** -> if I switch I get the log in page (which is not for submitter) then if I click previous I am on the right page again and language as been switched but with wrong page title- it keeps the "log in" page title : 
![Kapture 2022-08-03 at 14 57 29](https://user-images.githubusercontent.com/89908145/182613840-8e752d82-a93e-45e5-995a-fe0a7bbdb46e.gif)

-> Submitter should never see the login page, the language switch should work as it used to work (meaning same page just in other language)

**Comment by noelmace** [comment]
The consent text hasn't been internationalised. When I modify the text, both versions (en and fr) are modified. No form can therefore be tested.

![image](https://user-images.githubusercontent.com/7578400/185800728-515d6811-bcfc-47ee-af0a-bcfa692a5f75.png)
![image](https://user-images.githubusercontent.com/7578400/185800763-6bc095c1-28d1-4fb7-b3b8-b393dc107008.png)

![image](https://user-images.githubusercontent.com/7578400/185800703-b5641535-f2a9-4f9a-87bf-bb3f1f7342cf.png)

**Comment by noelmace** [comment]
Moved to v1.0.13 to avoid blocking v1.0.12 release.

@timnicblind & @loncarb: internationalisation needs extra attention in v1.0.13, as several features seem buggy / only partially addressed here. Please create an epic for all related issues (including those already addressed) to help track this.

**Comment by timnicblind** [comment]
After testing internalisation of text in the mentioned sections is good for me now
