### ISSUE TITLE
[Interim Spectacle Application form] Step 1- change "means of transportation" field to not mandatory

### ISSUE THREAD

**Issue by Clementinev** [blindnet-io/product-management#835]
(following https://github.com/blindnet-io/product-management/issues/801)

The field "Do you have a means of transportation (personal vehicle)?"/"Avez-vous un moyen de déplacement (véhicule personnel) ?" should be changed to **not mandatory field**

**Comment by noelmace** [comment]
As this issue is "implemented", has a high priority, and no milestone has been defined, I by default consider it will be part of the v1.0.9 release.

@IvanaT0mic please update the milestone if not.
