### ISSUE TITLE
[Interim Spectacle Application form] Step 1 - typo on sending form email

### ISSUE THREAD

**Issue by Clementinev** [blindnet-io/product-management#836]
(following https://github.com/blindnet-io/product-management/issues/801)
On the english email that is sent by Data Consumer through pf to a submitter to fill a form, delete "form" duplicate on the name of the form : 
<img width="682" alt="Screenshot 2022-07-25 at 15 16 01" src="https://user-images.githubusercontent.com/89908145/180794527-d3931603-d6a2-49bd-9936-4819d4e6db33.png">

**Comment by noelmace** [comment]
As this issue is "in progress", has a high priority, and no milestone has been defined, I by default consider it will be part of the v1.0.9 release.

@IvanaT0mic please update the milestone if not.
