### ISSUE TITLE
Email language for Submitters emails should be in the language they chose to fill in form/submit privacy request

### ISSUE THREAD

**Issue by Clementinev** [blindnet-io/product-management#839]
Following https://github.com/blindnet-io/product-management/issues/791

Submitters should receive emails in the language they chose to fill in a form/submitting a privacy request e.g. confirmation email for a form must be send in the chosen language the form has been filled

**Comment by noelmace** [comment]
Still not working: I submitted several forms in french (RE/MAX Avantage - Dossier Vendeur, Holtrop SLP, and others), and still received emails in English. I use fr by default (don't select English then reselect french), and always receive emails in English.

**Comment by noelmace** [comment]
Moving to v1.0.13 in order to avoid blocking v1.0.12 release. @timnicblind please retest this when possible.
