### ISSUE TITLE
Reconsider Data Subject Identity Representation in PRIV

### ISSUE THREAD

**Issue by milstan** [blindnet-io/product-management#840]
Data Rights Protocol (specific to CCPA, the compatibility with which is covered [here](https://github.com/blindnet-io/product-management/blob/db3de3fda664084fb67c77b4287867bcb281eded/refs/schemas/compatibility.md#data-rights-protocol)), uses a slightly different way to represent Data Subject Identities. See [their way](https://github.com/consumer-reports-digital-lab/data-rights-protocol#304-schema-identity-encapsulation)

Our way, [described here](https://github.com/blindnet-io/product-management/blob/main/refs/schemas/priv/RFC-PRIV.md#decentralized-identity-of-data-subjects) might be a bit unusual. 

## Intended outcome

The goal of this issue to reach a decision if whe should:
- align with DRP,
- introduce compatibility (be able to work with both ways)
- just ignore it.

## Context

Allow people not using our Privacy Request Multicast Protocol, to use DRP's Endpoint Specification (or even use it ourselves) in combination with PRIV terms (instead of DRP's Data Schemas objects).

Please discuss, and make changes as you see fit.

**Comment by m4rk055** [comment]
DRP requires implementation of the OpenID protocol to identify users.
Having simply user ids is more flexible but more prone to errors, as systems need to synchronize how they identify a user.

**Comment by milstan** [comment]
We need to support woth systems that use OpenID and those that don't.

So @m4rk055 what is your opinion concretely, how to model this for maximal flexibility?

IMHO, it is ok to have the model flexible, and let systems exchanging data to agree on how to identify the users.

**Comment by milstan** [comment]
After discussion with @m4rk055 over slakc we concluded that due to our need to support both OpenId and non-OpenId authentication systems, we have the interest to keep the current design.

@TheKinrar if you agree just close this issue.

**Comment by milstan** [comment]
Decision has been made implicitely. This issue is now obsolete.
