### ISSUE TITLE
SQL script to add a form to a user

### ISSUE THREAD

**Issue by m4rk055** [blindnet-io/product-management#842]
Currently, a form is added for a PF user manually in the database. This should be automated and the first step is creating an SQL script to do it.
Script should accept user's email address and form id as inputs and populate relevant tables.

**Comment by Clementinev** [comment]
Can you please reference the link to the script in the issue ? @loncarb

**Comment by loncarb** [comment]
here you go
https://github.com/blindnet-io/privateform-server/blob/develop/Scripts/AddNewFormLinkToUser.sql

**Comment by noelmace** [comment]
Thx. As you (@loncarb) are now responsible for running this script, I'm considering this issue solved without any need for further review.
