### ISSUE TITLE
Add localization for custom form consents

### ISSUE THREAD

**Issue by m4rk055** [blindnet-io/product-management#843]
Custom consents of user's form are not localized.
Add localization to them similarly to consent description.

**Comment by loncarb** [comment]
What should we do for current data in `FormCustomConsents` because they are not localized. 
When we add new table for localization we will delete column where actual text is saved just where we should move that text, to `fr` translation?

**Comment by m4rk055** [comment]
Moving it to `fr` translation is ok.

**Comment by loncarb** [comment]
I cannot connect to prod or staging db, I'm getting time out exception. Did we changed dbs on azure or credentials?

**Comment by TheKinrar** [comment]
> I cannot connect to prod or staging db, I'm getting time out exception. Did we changed dbs on azure or credentials?

Should be fixed now.

**Comment by noelmace** [comment]
@loncarb should we move this to v1.0.12, or can you fix it and release v1.0.11 by tomorrow?

**Comment by loncarb** [comment]
@noelmace with which form did you have problems? in db it looks ok and on my account it looks ok

**Comment by noelmace** [comment]
@bogdan: all of them. See https://github.com/blindnet-io/product-management/issues/839#issuecomment-1221575615 and https://github.com/blindnet-io/product-management/issues/832#issuecomment-1221577127.

**Comment by loncarb** [comment]
I'm having troubles accessing DB again, it is the same timeout error

**Comment by noelmace** [comment]
@loncarb is your access to the DB solved or should I do anything for you?

**Comment by TheKinrar** [comment]
@noelmace It was solved, and I believe we shared the "procedure" we're using to "fix" the issue with @loncarb.

**Comment by noelmace** [comment]
I'm moving this issue to _ready_ then.

**Comment by Clementinev** [comment]
It works on my side but not relevant anymore due to #922
