### ISSUE TITLE
Privateform - wrong form name in email

### ISSUE THREAD

**Issue by noelmace** [blindnet-io/product-management#847]
> version: v1.0.8, in production

When sending a "Loreto form" email, the email shows the wrong form name:
![image](https://user-images.githubusercontent.com/7578400/181220171-53c3ceb8-665f-480f-8f46-d4563b1ccf2e.png)
The link's URL is still the right one tho.

Make sure this doesn't happen with other forms too.

**Comment by Clementinev** [comment]
Change the embedded text with the URL with the form **title** for all forms : 
- [Sagan]: should be "Retard de justice"/"Delay of Justice"
- [Holtrop]: no changes
- [Sharpstone Advisory]: "Sharpstone Advisory"/"Sharpstone Advisory"
- [Sharpstone Advisory]: "Sharpstone Capital"/"Sharpstone Capital"
- [Loretto 1 form/locataire]: "Dossier Locataire"/"Rental file"
- [Loretto 2 Propriétaire]: "Dossier de mise en location d'un appartement"/ "File to put an apartment in rent"
- [Loreto 3 Vendeur]: "Dossier de vente"/ "Sales file"
- [Loreto 4 Acheteur]: "Offre d'achat"/"Bid"
- [Interim Spectacle Application form]: "Dossier de candidature" / "Application form"
- [RE/MAX Avantage 1 Dossier vendeur]: "Dossier de vente"/ "Sales file"
- [Skill Hunter CV]: "Skill Hunter CV"/"Skill Hunter Resume"

**Comment by noelmace** [comment]
@Clementinev I believe the name here is directly linked to the one in #848, so no need to add an additional overread by using different names or localisation here, especially as this is a high-priority bug in production.

Please open another issue to address the localisation of the email and related variables (including the form name), which would IMHO be a new feature with low ("necessary") priority.

**Comment by Clementinev** [comment]
For some form backoffice name = title of the form for end-user but for some others it is not the same : for example Sharpstone whant Sharpstone Adviosry as backoffice name and the title of the form that the end-user has to submit is "Déposer votre information" or for Loreto, the backoffice name "Dossier Propriétaire" is not the title that the end-user is going to see, he's going to see "Dossier de mise en location d'un appartement"

**Comment by Clementinev** [comment]
I'll create a new issue for all the forms, separated from Loreto's one, that needs to be resolved quickly

**Comment by noelmace** [comment]
@Clementinev Clarification: this issue is about the fact that the form name in the email (Sharpstone) **doesn't match** the actual form URL (Loreto). That it. Please keep the discussion in this scope here.

@loncarb How is this form name handled exactly? In code or DB? Are there two separate values for the back office (see #848) and in this email or not?

**Comment by noelmace** [comment]
https://github.com/blindnet-io/product-management/issues/847#issuecomment-1197845144 isn't off-topic, as I realise the email should indeed use the form **title** (e.g. "Dossier de mise en location d'un apartment") instead of its "technical name" (e.g. "Loreto Form").

**Comment by loncarb** [comment]
It is handled in database. Every email that is sent is in database and we have structure in DB that every consumer has his own email for each form, this functionality is missing on frontend and as these tasks start to add up we should implement frontend feature for consumer to change those emails like he has ability to change description or consents

**Comment by noelmace** [comment]
No client asked for a custom email template since I took back solution engineering, so I have no strong opinion regarding the priority of https://github.com/blindnet-io/product-management/issues/416

**Comment by Clementinev** [comment]
Remove FR:"questionnaire" and EN:"form" word :
<img width="550" alt="Screenshot 2022-08-04 at 12 19 40" src="https://user-images.githubusercontent.com/89908145/182824404-56e76544-70d9-4528-aca9-2a5af7d241d9.png">
<img width="551" alt="Screenshot 2022-08-04 at 12 19 45" src="https://user-images.githubusercontent.com/89908145/182824407-c767802b-6792-442a-bb8a-b1832f5adebb.png">
