### ISSUE TITLE
Privateform - define better form names

### ISSUE THREAD

**Issue by noelmace** [blindnet-io/product-management#848]
> version: v1.0.8, in production
> account: noel@blindnet.io

Form names should reflect the Client's Use Case, with the end user in mind.

![Image](https://user-images.githubusercontent.com/7578400/181376656-20dd962f-6572-4168-95c0-8a1ea640daa5.png)

Having names like "[client] form" for a client with 4 different forms covering clear and well-defined use cases is unacceptable, as they can't clearly identify the correct form for each use case.

I'm considering this as a bug as it lead to a poor UX and was an obvious requirement in the first place.

The best default option seems to be "[Client's name] - [Form name (in client's main language) if necessary]".

For the pre-existing ones in my account, this gives:
- Sagan Avocats ➡  "Sagan Avocats - Retard de justice"
- Holtrop Form ➡ "Holtrop SLP"
- Sharpstone advisor form ➡ "Sharpstone Advisory" (as requested by the client)
- Sharpstone Form ➡ "Sharpstone Capital" (as requested by the client)
- Loreto form ➡ (https://github.com/blindnet-io/product-management/issues/787) "Loreto Immobilier - Dossier Locataire"

For in in progress ones:
- https://github.com/blindnet-io/product-management/issues/813 : "Loreto Immobilier - Dossier Propriétaire"
- https://github.com/blindnet-io/product-management/issues/817 : "Loreto Immobilier - Dossier Vendeur"
- https://github.com/blindnet-io/product-management/issues/818 : "Loreto Immobilier - Dossier Acheteur"
- https://github.com/blindnet-io/product-management/issues/801 : "Interim Spectacle - Dossier de candidature"
- https://github.com/blindnet-io/product-management/issues/823 : "RE/MAX Avantage - Dossier Vendeur"
- https://github.com/blindnet-io/product-management/issues/841: "Skill Hunter - CV"

**Comment by Clementinev** [comment]
Change form backoffice name to the following : 
- [[Loretto 1 Locataire] ](https://github.com/blindnet-io/product-management/issues/787) : "Dossier Locataire"
- [[Loreto 2 Propriétaire]](https://github.com/blindnet-io/product-management/issues/813) : "Dossier Propriétaire"
- [[Loreto 3 Vendeur]](https://github.com/blindnet-io/product-management/issues/817) : "Dossier Vendeur"
- [[Loreto 4 Acheteur]](https://github.com/blindnet-io/product-management/issues/818) : "Dossier Acheteur"
- [[Interim Spectacle Application form]](https://github.com/blindnet-io/product-management/issues/801) : "Dossier de candidature" 
- [[RE/MAX Avantage 1 Dossier vendeur]](https://github.com/blindnet-io/product-management/issues/823) already OK
- [[Skill Hunter CV] ](https://github.com/blindnet-io/product-management/issues/841): "Formulaire CV"

We will have to be carful on our side to check the url name to know which form correspond to which client

**Comment by noelmace** [comment]
I'm OK with something like "[client name] - [form name]", as removing the client name would indeed make testing and demoing way more complicated.

**Comment by Clementinev** [comment]
Alright then ignore my last comment and change form backoffice name to the following :
- [[Loreto 1 Locataire] ](https://github.com/blindnet-io/product-management/issues/787) : "Loreto immobilier - Dossier Locataire"
- [[Loreto 2 Propriétaire]](https://github.com/blindnet-io/product-management/issues/813) : "Loreto immobilier - Dossier Propriétaire"
- [[Loreto 3 Vendeur]](https://github.com/blindnet-io/product-management/issues/817) : "Loreto immobilier - Dossier Vendeur"
- [[Loreto 4 Acheteur]](https://github.com/blindnet-io/product-management/issues/818) : "Loreto immobilier - Dossier Acheteur"
- [[Interim Spectacle Application form]](https://github.com/blindnet-io/product-management/issues/801) : "Interim Spectacle - Dossier de candidature" 
- [[RE/MAX Avantage 1 Dossier vendeur]](https://github.com/blindnet-io/product-management/issues/823) : "RE/MAX Avantage - Dossier Vendeur
- [[Skill Hunter CV] ](https://github.com/blindnet-io/product-management/issues/841): "Skill Hunter - CV"

**Comment by noelmace** [comment]
@Clementinev I already updated this issue description for that :wink: Please just make sure it's OK with you, update it yourself if necessary, and then, hide your last comment as "outdated". Thx
