### ISSUE TITLE
[Loreto 1 Locataire] Improvements after client demo meeting

### ISSUE THREAD

**Issue by Clementinev** [blindnet-io/product-management#849]
Here are the following improvements : 

**on Page 1**:
**1.** put the following fields as **non mandatory**: 
   - "Deux derniers avis d’imposition :" / "Two last tax notices:" 
   - "Trois dernières quittances de loyer ou dernière taxe foncière :" / "Three last rent receipts or last property tax:" 

**on Page 3**:
**2.** Add the note : "Si cette partie ne vous concerne pas, vous pouvez passer à la page suivante" / "If it does not concern you, you can go to the nest page" in italic (such as on page 2) 
**3.** Make all fields on the page **non mandatory**
**4.** **Change field name label** of : "Photocopie de votre pièce d’identité (CNI ou passeport):" / "Photocopy of your identity document (CNI or passport):" **to "Photocopie de la pièce d’identité (CNI ou passeport) des garants, ou document Visal, Garantme, ou affilié :" / "Photocopy of identity document (CNI or passport) of the person(s) standing security, or Visal document, Garantme, or or affiliate:"**

**on new a page 6**
**5.** Add a new page 6 at the end of the form (page7 would be submission page with legal consent and email) with the following elements : 
   - **Sub title:** "Renseignements complémentaires" / "Further information"
   - **Radio button field:** "Durée de location souhaitée" / "Desired rental period" with : 
         - Radio button 1: "6 mois" / "6 months"
         - Radio button 2: "9 mois" / "9 months"
         - Radio button 3: "1 an renouvelable" / "1 year renewable"
   - **Radio button field:** "Je recherche une résidence" / "I am looking for a" with : 
         - Radio button 1: "Principale" / "Main home"
         - Radio button 2: "Secondaire" / "Second home"
         - Radio button 3: "Bail code civil (entreprise)" / "Civil code lease (company)" 
   - **Date field:** "Date souhaitée d'entrée dans les lieux" / "Desired date of entry into the premises"
   - **Multiple file upload field:** "Documents supplémentaires (tout document qui vous semble utile)" / "Additional documents (any document you find useful)"
   - **Long text field** "Parlez-nous de vous" / "Tell us about you"

**Comment by IvanaT0mic** [comment]
For page no.6 we have file upload. Could you provide file name pattern? @Clementinev

**Comment by Clementinev** [comment]
Yes for Multiple file upload field: "Documents supplémentaires (tout document qui vous semble utile)" / "Additional documents (any document you find useful)"
-> file name = FR: "document-supplementaire" EN: "additional-document"

**Comment by Clementinev** [comment]
Everything works well- there is just this small typo to fix (double "or") p.3 and in PDF :
<img width="1440" alt="Screenshot 2022-08-03 at 15 40 31" src="https://user-images.githubusercontent.com/89908145/182624160-a92772de-4291-4d6d-9df6-b255a1dba517.png">
<img width="659" alt="Screenshot 2022-08-03 at 15 45 50" src="https://user-images.githubusercontent.com/89908145/182624168-edad4ae9-ceea-42a1-bbef-c1055137e3c4.png">
