### ISSUE TITLE
Chromium crash

### ISSUE THREAD

**Issue by m4rk055** [blindnet-io/product-management#850]
When I select a file with name containing non-ASCII characters, Chromium crashes.
Works in Firefox.

**Comment by nikolaFusion** [comment]
@noelmace @m4rk055 On which page the bug occurs? I can to select file with non-ASCII characters ( "的 的¤§.txt"). For me works on Chrome, Edge and Firefox.

**Comment by m4rk055** [comment]
@nikolaFusion While filling out the [Sagan form](https://stage.form.blindnet.io/sagan/3739348f-1b62-40d0-8df6-a526391adaa9) as a data subject in Chromium: [recording.webm](https://user-images.githubusercontent.com/71560916/184822482-9b2ab715-ee03-4deb-a074-39b78a8d9b55.webm)

**Comment by loncarb** [comment]
@m4rk055 what is your version of chrome? are you using mac? or is that linux? we dont get that error on windows

**Comment by m4rk055** [comment]
`Version 102.0.5005.61 (Official Build) Arch Linux (64-bit)`

It might be an issue with the Chromium build, not PF. Closing the issue.
