### ISSUE TITLE
Add search by "apartment" field feature for real estate clients

### ISSUE THREAD

**Issue by Clementinev** [blindnet-io/product-management#858]
**Only for Real Estate clients** such as [Loreto Immobilier] and [RE/MAX Avantage] we need to **add a new search field by FR:"Appartement" / EN: "Apartment" field** on their privateform account such as sketch below

"Apartment" field is a free text field inside of the forms so submitter can input the address or street name of the apartment

**Clients need to be able to fuzzy search by FR:"Appartement" / EN: "Apartment" field**

![Frame 577](https://user-images.githubusercontent.com/89908145/181590022-4c117353-d97f-4d83-84ca-31ebb3c8f0f4.png)

**Comment by loncarb** [comment]
With current implementation this is not possible because search functionality is searching forms only form metadata and in metadata we are not storing "apartment". We can put it to metadata but then all previously entered forms will not be searchable by apartment

**Comment by m4rk055** [comment]
It's ok to put the apartment field into the metadata. Since there is not production data, you can just ignore the old forms.

**Comment by Clementinev** [comment]
It is working well! Before closing the issue I want to make sure it is possible to put this search field only on some clients pf accounts and not all others pf accounts ? @loncarb

**Comment by loncarb** [comment]
It is not configurable to end user but it will only show if user has some of these forms
- Loreto Immobilier - Dossier Locataire
- Loreto Immobilier - Dossier Acheteur
- RE/MAX Avantage - Dossier Vendeur
- Loreto Immobilier - Dossier Vendeur

**Comment by noelmace** [comment]
This answer the initially specified need, which is why I'm considering this issue done and closing it.
We'll still need to improve that with other issues.
