### ISSUE TITLE
Implement eligible privacy scope calculator

### ISSUE THREAD

**Issue by m4rk055** [blindnet-io/product-management#874]
Data subject's eligible privacy scope is used to respond to TRANSPARENCY requests and make recommendations for other types of requests.
EPS is calculated from legal base events (start/finish), consents and some privacy requests (OBJECT, RESTRICT and REVOKE-CONSENT).

More information on EPS can be found in the [expected behavior document](https://github.com/blindnet-io/product-management/blob/main/refs/schemas/priv/expected-behavior.md).

**Comment by milstan** [comment]
I suspect this issue to be done. I am closing it. @m4rk055 feel free to reopen if needed.
