### ISSUE TITLE
[privateform] show current version

### ISSUE THREAD

**Issue by noelmace** [blindnet-io/product-management#880]
## Context

- Privateform releases are now tracked with clear [milestones](https://github.com/blindnet-io/product-management/milestones) for each release
- There is no release management whatsoever in the code base (see https://github.com/blindnet-io/privateform-web-client/blob/main/package.json, where the version is still 0.0.0) BUT **this issue isn't directly related to that**

## Description

In the frontend application, add the current version number link to the ["secondary menu"](https://github.com/blindnet-io/privateform-web-client/blob/fe41ef2df03695859b4da28bdc3ee0d30f0cdf15/src/app/app.component.html#L102-L122), pointing to the related milestone in Github (e.g. https://github.com/blindnet-io/product-management/milestone/51 for v1.0.10).

![image](https://user-images.githubusercontent.com/7578400/184103459-a549fe19-0716-49d1-8ea2-b9cdec64e011.png)

> Of course, the front and colour of this new link should be the same as the one used for the other items of this menu.

## Requirements

- [ ] the version number and URL should be easy to find and update in the code base
- [ ] @noelmace: add this step/requirement to the [privateform release management policy](https://github.com/blindnet-io/clients-management/blob/main/docs/privateform-release-management.md)

> **Warning**
>
> The version number and URL should be the first thing to be updated **on staging** right after each release to production.
>
> This issue is only here to track the **first** step (adding the current version number to the menu) and will be closed after completing it.
>
> Updating the version number afterwards will be considered a **mandatory** part of the release management process. Having an up-to-date version number will be a very strong requirement for each release.

**Comment by m4rk055** [comment]
There was an [issue to remove](https://github.com/blindnet-io/product-management/issues/467) the version number.
@Vuk-BN does it apply only for the versions starting with 0?

Personally, I like having the version number indicated in the app.

**Comment by noelmace** [comment]
I indeed wasn't aware of this issue. Context has changed a lot since.

Versions numbers **are** communicated to our clients, so this **is** valuable information for them.

See #881: IMHO, reporting issues with "on staging" or "on prod" labels make no sense. Our products have clear versioning, so issues should be associated with a version when reported. 

This is especially why I personnaly need a version number clearly shown on Privateform.

**Comment by noelmace** [comment]
@loncarb updating the version on staging after each release on production is now a requirement.
Please don't forget to do it :pray:

**Comment by loncarb** [comment]
what should be version on staging? the new current version that is in development or version that is on production?

**Comment by m4rk055** [comment]
It should be the version from the current milestone - usually patch version of the production + 1.

**Comment by noelmace** [comment]
To be even clearer: the version number should be incremented on staging **right after** each release on production.
