### ISSUE TITLE
⚙️ [Project]: Loreto - Acheteur

### ISSUE THREAD

**Issue by noelmace** [blindnet-io/product-management#888]
## Description

| Client's Epic         | https://github.com/blindnet-io/clients-management/issues/34 |
| --------------------- | ---- |
| Client's Requirements |  https://github.com/blindnet-io/clients-management/issues/49 |

Allow buyers to send information to Loreto.

## Sub-tasks

- [x] https://github.com/blindnet-io/product-management/issues/818
- [x] https://github.com/blindnet-io/product-management/issues/889

## Stakeholders

- SE Officer: @noelmace 
- Account management: @earvinblindnet 
- Product/User Experience: @Clementinev

**Comment by earvinblindnet** [comment]
@Clementinev @noelmace I had the final demo with Juliette from Loreto Immobilier and she's ready to use Privateform. She just has two requests. 

The first one is about the possibility to add a box for the notary's contact details. 

The second one is about the possibility to add the Loreto Immobilier logo to the downloaded form through the received form. 

How long do you think it could take ?

**Comment by milstan** [comment]
done
