### ISSUE TITLE
✨ [Loreto - Acheteur] reshape and improve the form

### ISSUE THREAD

**Issue by noelmace** [blindnet-io/product-management#889]
### Which blindnet product(s) are relevant/related to the feature/enhancement request?

Privateform (form.blindnet.io)

### Does it seem to be a simple enhancement of an existing feature?

Yes

### Description

Based on a first demo, Loreto wants to reshape and improve their "Acheteur" form.

### Proposed solution

- keep "first name", "last name" and "CNI" fields as is
- add a new text field for the address of the buyer - text: "Adresse de résidence effective" / "Current residential address" 
- add a new date field - text: "Date de visite" / "Visit date"
- replacethe field title "Offre/bid" with "Proposition de prix (honoraires d'agence inclus)" / "Price proposal (including fees)"
- add a new text field - "Les fonds alloués à ce projet immobilier proviennet de" / "The funds allocated to this real estate project come from"
- add a new Yes/No field (switch or 2 exclusive options) - text: "Cette offre est formulée" / "This offer is made"
    - option 1 : "sans condition suspensive d'obtention d'un financement bancaire." / "without the condition precedent of obtaining bank financing."
    - option 2 : "sous condition suspensive d'obtention d'un financement bancaire" /  "with the condition precedent of obtaining bank financing."
    - IF AND ONLY IF option 2 is selected, show an additional text field : "Financement bancaire d'un montant maximum de" / "Bank financing for a maximum amount of"

### Alternatives considered

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by noelmace** [comment]
![image](https://user-images.githubusercontent.com/7578400/185600497-a4e6e958-2200-48d8-9dc9-8dbf731c745a.png)

There was a typo in the specs. Sorry for that.
It should be "Les fonds alloués à ce projet immobilier **proviennent** de instead

**Comment by noelmace** [comment]
@earvinblindnet once this is released on production, please demo it to the client as I'll be on vacation.
@Vuk-BN and @timnicblind will do the tests and coordination with Fusion while I'm on vacation, so just ping them if you need anything. Thx

**Comment by earvinblindnet** [comment]
The other forms have been shown or do we only need to demo this one ?

**Comment by timnicblind** [comment]
@loncarb @IvanaT0mic is this already ready for testing?

**Comment by loncarb** [comment]
it is on staging now

**Comment by timnicblind** [comment]
@loncarb can you put me this form in the account earvin@blindnet.io ?

**Comment by loncarb** [comment]
you should have it now

**Comment by timnicblind** [comment]
All is good now

**Comment by earvinblindnet** [comment]
@Clementinev @noelmace @loncarb I had the final demo with Juliette from Loreto Immobilier and she's ready to use Privateform. She just has two requests.

The first one is about the possibility to add a box for the notary's contact details.

The second one is about the possibility to add the Loreto Immobilier logo to the downloaded form through the received form.

How long do you think it could take ?

**Comment by loncarb** [comment]
@earvinblindnet Can you send me logo and where it should be placed and that thing regarding box i do not understand, can you upload here a picture in paint or whatever just to understand what kind of box

**Comment by earvinblindnet** [comment]
@loncarb It will be this logo and it should placed at the top left of the document : 
![loreto logo](https://user-images.githubusercontent.com/100844191/187687343-0ebe6396-9a4f-45c6-bc60-581abda0b9ef.png)

##

![image](https://user-images.githubusercontent.com/100844191/187687644-2f03f901-6296-4113-aa65-8099d3dcc477.png)

A box like the "appartement" one.

**Comment by noelmace** [comment]
@earvinblindnet in the future, please open a dedicated issue for each additional feedback using the dedicated templates so that we can discuss and plan it, and avoid reworking the existing issues.

**Comment by loncarb** [comment]
Hey I'm still not sure where to put the box.
What is `notary's contact details` ?

Did you mean to put something like box marked in red to put it around stuff marked with blue?


![Image](https://user-images.githubusercontent.com/10289559/188086811-14d7acea-6ed7-49b0-9f3f-7af2d8d025be.png)

**Comment by noelmace** [comment]
Has v1.0.12 is now past due by two weeks, I'm moving this to v1.0.14 (to be released next week).

**Comment by Clementinev** [comment]
Fox the 

> Hey I'm still not sure where to put the box. What is `notary's contact details` ?

"Notary's contact details" is not there at the moment -> we need to add a new text field "Notary's contact details"/"Coordonnées du Notaire"

**Comment by Clementinev** [comment]
- The Notary's contact box is working well
- **The logo is missing on the top left of the PDF**
