### ISSUE TITLE
Test .NET SDKs

### ISSUE THREAD

**Issue by m4rk055** [blindnet-io/product-management#894]
Since the last development on the .NET SDKs ([framework](https://github.com/blindnet-io/sdk-dotnet-framework-server), [client](https://github.com/blindnet-io/sdk-dotnet-client) and [server](https://github.com/blindnet-io/sdk-dotnet-core-server/tree/main)) was a long time ago, verify compatibility with the blindnet API and write down what needs to be updated and added.

**Comment by noelmace** [comment]
@jovana-todorovic @m4rk055 could you please share the links to these documents so we can close this issue?
