### ISSUE TITLE
✨ [privateform Sagan] simplification / improvement

### ISSUE THREAD

**Issue by noelmace** [blindnet-io/product-management#899]
> follow https://github.com/blindnet-io/clients-management/issues/51

### Which blindnet product(s) are relevant/related to the feature/enhancement request?

Privateform (form.blindnet.io)

### Does it seem to be a simple enhancement of an existing feature?

Yes

### Description

Sagan's privateform "retard de justice" needs to be simplified and extended following the client's request.

(feedback based on Privateform v1.0.10)

### Screen 1: add fields

Add two new mandatory fields:

- Adresse e-mail / Email address (with email validation)
- Numéro de téléphone / Phone number (with international and national phone number validation)

### Screen 2 : new last screen for answer "no"

> "Procédure devant le Conseil de prud’hommes"/"Process with National Labor Council"** section (after having answered "oui"/"yes" to first question "Avez-vous engagé une procédure devant le Conseil de prud'hommes contre votre employeur?"/"Have you initiated proceedings before the National Labor Council against your employer?")

For the question: "Avez-vous eu la décision du Conseil de prud'hommes dans votre affaire ?"/"Have you had the decision of the National Labor Council in your case? ":
<img width="600" alt="Screenshot 2022-07-11 at 17 17 01" src="https://user-images.githubusercontent.com/89908145/178298150-11395d4b-b06d-47b5-bb3d-7308cab2e48b.png">

IF the answer is: "Non pas encore"/"Not yet"

THEN :arrow_right: show a **LAST** screen with the following message:

> _:fr: french version :fr:_
>
> Votre dossier n’est pas encore éligible à l’indemnisation des retards de justice.
>
> Nous vous invitons à renseigner le formulaire quand vous aurez la décision du Conseil de prud’hommes.
>
> Pour toute information, veuillez nous contacter au 01 88 24 11 00.
>
> _:gb: english version :gb:_
>
> Your dossier is not yet eligible for compensation for a delay of justice.
>
>We invite you to fill in this form when you have the decision of the Labor Court.
>
> For any information, please contact us on 01 88 24 11 00.

:warning: the data submitter should not be able to submit the form in this case

### Screen 3 : add subtitle

> For the question: "Avez-vous eu la décision du Conseil de prud'hommes dans votre affaire ?"/"Have you had the decision of the National Labor Council in your case? ", when the answer is yes.
>
> ![image](https://user-images.githubusercontent.com/7578400/185080850-999e8adc-e02d-4bb5-b501-a12da41cc3b8.png)

Above "Est-ce qu'il y a eu un appel de la décision du Conseil de prud'hommes ? * " (see red line)

:arrow_right: add a new subtitle: "Procédure devant la Cour d’appel" / "Court of Appeal"

### Screen 5, "Procédure devant la cour d’appel": remove steps if NO
  
> "Procédure devant la Cour d’appel"/"Proceedings before the Court of Appeal" section** (after having answered "oui"/"yes" to first question "Avez-vous engagé une procédure devant le Conseil de prud'hommes contre votre employeur?"/"Have you initiated proceedings before the National Labor Council against your employer?",
then "oui"/"yes" to "Avez-vous eu la décision du Conseil de prud'hommes dans votre affaire ?"/"Have you had the decision of the National Labor Council in your case? ",
then "oui"/"yes" to "Est-ce qu'il y a eu un appel de la décision du Conseil de prud'hommes ?"/"Have you filed an appeal to the decision?")
>
> **For question : "Avez-vous déjà la décision de la Cour d'appel dans votre affaire ?"/"Do you already have the decision of the Court of Appeal in your case?"**:
>
> ![image](https://user-images.githubusercontent.com/7578400/185082814-4c9589e3-5c9c-44ef-94df-07217850ef27.png)

IF answer is:** "Non"/"No"

THEN :arrow_right:  directly go to the last screen of the form** (to enter email address and submit form) 

AND :arrow_right: **delete all following screen**:

<img width="1440" alt="Screenshot 2022-07-11 at 17 38 14" src="https://user-images.githubusercontent.com/89908145/178302264-f28f19bf-3d16-4b90-aa71-7a4e13f09167.png">

### Alternatives considered

These requirements have been directly expressed by the client after several back and forth.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by IvanaT0mic** [comment]
In the task, it was said that by clicking on "not yet" a new view should be added that disables sending the form (Screen 2).
![slika1](https://user-images.githubusercontent.com/102587557/185932146-b74c0a6e-cb9c-4f6c-8327-936ef12b8b32.png)

 Inserting that view deletes the following pages.

![slika2brisi](https://user-images.githubusercontent.com/102587557/185932236-966aff68-14fb-4232-acbf-fa3ab8b58799.png)
![slika3brisi](https://user-images.githubusercontent.com/102587557/185932241-66821638-a362-4f42-b354-a3f59040a018.png)
![slika4brisi](https://user-images.githubusercontent.com/102587557/185932243-2d6b4882-37b1-4daf-a51a-e1ed803ef748.png)

Should they be added somewhere else or deleted from the form?
@earvinblindnet @timnicblind @Vuk-BN

**Comment by timnicblind** [comment]
@IvanaT0mic they should be deleted from the form if clicking **"Non pas encore"**. 

However they should continue to appear on the other path, clicking **"Oui"**. 




When clicked **"Non pas encore"** only the page with writen this should appear: 

🇫🇷 french version 🇫🇷

Votre dossier n’est pas encore éligible à l’indemnisation des retards de justice.

Nous vous invitons à renseigner le formulaire quand vous aurez la décision du Conseil de prud’hommes.

Pour toute information, veuillez nous contacter au 01 88 24 11 00.

🇬🇧 english version 🇬🇧

Your dossier is not yet eligible for compensation for a delay of justice.

We invite you to fill in this form when you have the decision of the Labor Court.

For any information, please contact us on 01 88 24 11 00.

**Comment by IvanaT0mic** [comment]
@timnicblind 
Not a single path leads to them anymore

I found a flow of views based on the chosen route so that you can find the place where they should appear and how to get to them

![structure](https://user-images.githubusercontent.com/102587557/185936420-3953e3fc-de69-4936-b950-c0e677cd5b19.png)

**Comment by Clementinev** [comment]
**1.** Phone number field on first page only validate international number format : 
<img width="600" alt="Screenshot 2022-09-01 at 13 13 57" src="https://user-images.githubusercontent.com/89908145/187901128-8ebc20fb-ade3-4529-af0c-0ddbd545b9dc.png">

**->** it should **valide both international and national phone number** ie +33122334455 and 0122334455
**->** the **validation message should be changed** to FR="Veuillez entrer un numéro de téléphone au format national (ex: 01 22 33 44 55) ou au format international (avec le signe (+) suivi du code pays et du numéro de téléphone local. Ex : +33 1 22 33 44 55)" / EN="Please enter a phone number in national format international format (e.g.: 01 22 33 44 55) or in international format (with a plus sign (+) followed by the digit country code and local phone number. E.g: +33 1 22 33 44 55)
