### ISSUE TITLE
[blindnet.dev] new specific auth tutorial

### ISSUE THREAD

**Issue by noelmace** [blindnet-io/product-management#980]
develop a small tutorial on how to work [with auth](https://github.com/blindnet-io/privacy-components-web/pull/165) and blindnet devkit, using https://github.com/blindnet-io/product-management/issues/963 as an example

> originally posted by @milstan on [Slack](https://blindnet.slack.com/archives/C02T66M01CG/p1665139548285939?thread_ts=1665138523.755659&cid=C02T66M01CG)

**Comment by noelmace** [comment]
As discussed with @milstan and @blindnet-io/engineering during the Tech Talk on October 7th, this issue has a high priority, and should be done in parallel of #963 right after https://github.com/blindnet-io/devrel-management/issues/89

**Comment by milstan** [comment]
@TheKinrar this is probably a duplicate issue with what you are already doing. Just close it when done.
