### ISSUE TITLE
📌 Add authentication to demo

### ISSUE THREAD

**Issue by TheKinrar** [blindnet-io/product-management#996]
While demo already has an authentication UI, it's completely client-side and therefore does not provide any authentication for server requests.

What needs to be done:
- Add API endpoint in the demo backend to exchange an email auth token for a blindnet token
- Use this endpoint in PRCI to authenticate users, then use the returned token to authenticate requests to PCE

We also need to authenticate DCI requests, but these are app-scoped, so it's a bit different, we don't need email verification. Instead, we need to:
- add an API endpoint (probably password-authenticated for demo purposes?) to get an app-scope blindnet token
- and then use this token for DCI requests to PCE

**Comment by milstan** [comment]
Same needs to be done on the [dogfood](https://github.com/blindnet-io/dogfood) Privacy Portal and Talent Portal
